/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Fleetguard\model.glb -o c:\Fleetguard\frontend\src\pages\landing\Model.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-3, 0, 0]}>
        <mesh geometry={nodes['001-diesel-pump-island0'].geometry} material={materials.steel} position={[0, 0.1, 0]} scale={2.5} />
        <mesh geometry={nodes['001-diesel-pump-island1'].geometry} material={materials.white} position={[0, 1, 0]} scale={1.775} />
        <mesh geometry={nodes['001-diesel-pump-island2'].geometry} material={materials.glass} position={[0, 1.445, 0.29]} scale={1.507} />
        <mesh geometry={nodes['001-diesel-pump-island3'].geometry} material={materials.trim} position={[0.488, 1.004, 0]} scale={1.535} />
      </group>
      <group position={[3, 0, 0]}>
        <mesh geometry={nodes['002-diesel-pump-island0'].geometry} material={materials.steel} position={[0, 0.1, 0]} scale={2.5} />
        <mesh geometry={nodes['002-diesel-pump-island1'].geometry} material={materials.white} position={[0, 1, 0]} scale={1.775} />
        <mesh geometry={nodes['002-diesel-pump-island2'].geometry} material={materials.glass} position={[0, 1.445, 0.29]} scale={1.507} />
        <mesh geometry={nodes['002-diesel-pump-island3'].geometry} material={materials.trim} position={[0.488, 1.004, 0]} scale={1.535} />
      </group>
      <group position={[-1.2, 0, 0]}>
        <mesh geometry={nodes['003-long-nose-sleeperwheel-0--1rubber'].geometry} material={materials.rubber} position={[-1.025, 0.5, 2.402]} scale={0.5} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-0-1rubber'].geometry} material={materials.rubber} position={[1.025, 0.5, 2.402]} scale={0.5} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-0--1alloy'].geometry} material={materials.alloy} position={[-1.095, 0.5, 2.402]} scale={0.31} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-1--1alloy'].geometry} material={materials.alloy} position={[-1.095, 0.5, -1.1]} scale={0.31} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-2--1alloy'].geometry} material={materials.alloy} position={[-1.095, 0.5, -2.2]} scale={0.31} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-0--1steel'].geometry} material={materials.steel} position={[-1.16, 0.5, 2.402]} scale={0.201} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-0-1steel'].geometry} material={materials.steel} position={[1.19, 0.5, 2.402]} scale={0.201} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-1--1steel'].geometry} material={materials.steel} position={[-1.16, 0.5, -1.1]} scale={0.201} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-1-1steel'].geometry} material={materials.steel} position={[1.19, 0.5, -1.1]} scale={0.201} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-2--1steel'].geometry} material={materials.steel} position={[-1.16, 0.5, -2.2]} scale={0.201} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-2-1steel'].geometry} material={materials.steel} position={[1.19, 0.5, -2.2]} scale={0.201} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-0-1alloy'].geometry} material={materials.alloy} position={[1.095, 0.5, 2.402]} scale={0.31} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-1-1alloy'].geometry} material={materials.alloy} position={[1.095, 0.5, -1.1]} scale={0.31} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-2-1alloy'].geometry} material={materials.alloy} position={[1.095, 0.5, -2.2]} scale={0.31} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-1--1rubber'].geometry} material={materials.rubber} position={[-0.895, 0.5, -1.1]} scale={0.5} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-2--1rubber'].geometry} material={materials.rubber} position={[-0.895, 0.5, -2.2]} scale={0.5} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-1-1rubber'].geometry} material={materials.rubber} position={[0.895, 0.5, -1.1]} scale={0.5} />
        <mesh geometry={nodes['003-long-nose-sleeperwheel-2-1rubber'].geometry} material={materials.rubber} position={[0.895, 0.5, -2.2]} scale={0.5} />
        <mesh geometry={nodes['003-long-nose-sleeper18'].geometry} material={materials.steel} position={[0, 1.509, 0.13]} scale={3.23} />
        <mesh geometry={nodes['003-long-nose-sleeper19'].geometry} material={materials.paint} position={[0, 1.725, 0.775]} scale={2.325} />
        <mesh geometry={nodes['003-long-nose-sleeper20'].geometry} material={materials.trim} position={[0, 1.005, 0.388]} scale={2.813} />
        <mesh geometry={nodes['003-long-nose-sleeper21'].geometry} material={materials.alloy} position={[0, 1.8, 0.658]} scale={2.563} />
        <mesh geometry={nodes['003-long-nose-sleeper22'].geometry} material={materials.glass} position={[0, 2.225, 0.879]} scale={1.5} />
        <mesh geometry={nodes['003-long-nose-sleepercab-door--1'].geometry} material={materials.paint} position={[-1.113, 1.64, 0.7]} scale={0.55} />
        <mesh geometry={nodes['003-long-nose-sleepercab-door-1'].geometry} material={materials.paint} position={[1.113, 1.64, 0.7]} scale={0.55} />
        <mesh geometry={nodes['003-long-nose-sleeper24'].geometry} material={materials.white} position={[0, 0.935, 3.19]} scale={0.955} />
        <mesh geometry={nodes['003-long-nose-sleeper26'].geometry} material={materials.accent} position={[0, 2.685, 1.2]} scale={0.805} />
        <mesh geometry={nodes['003-long-nose-sleeperfifth-wheel'].geometry} material={materials.steel} position={[0, 1.165, -1.3]} scale={0.45} />
      </group>
      <group position={[5, 0, 0]}>
        <mesh geometry={nodes['004-cabover-sleeperwheel-0--1rubber'].geometry} material={materials.rubber} position={[-1.025, 0.5, 0.95]} scale={0.5} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-0-1rubber'].geometry} material={materials.rubber} position={[1.025, 0.5, 0.95]} scale={0.5} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-1--1alloy'].geometry} material={materials.alloy} position={[-1.095, 0.5, -1.1]} scale={0.31} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-2--1alloy'].geometry} material={materials.alloy} position={[-1.095, 0.5, -2.2]} scale={0.31} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-0--1alloy'].geometry} material={materials.alloy} position={[-1.095, 0.5, 0.95]} scale={0.31} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-1--1steel'].geometry} material={materials.steel} position={[-1.16, 0.5, -1.1]} scale={0.201} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-1-1steel'].geometry} material={materials.steel} position={[1.19, 0.5, -1.1]} scale={0.201} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-2--1steel'].geometry} material={materials.steel} position={[-1.16, 0.5, -2.2]} scale={0.201} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-2-1steel'].geometry} material={materials.steel} position={[1.19, 0.5, -2.2]} scale={0.201} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-0--1steel'].geometry} material={materials.steel} position={[-1.16, 0.5, 0.95]} scale={0.201} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-0-1steel'].geometry} material={materials.steel} position={[1.19, 0.5, 0.95]} scale={0.201} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-1-1alloy'].geometry} material={materials.alloy} position={[1.095, 0.5, -1.1]} scale={0.31} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-2-1alloy'].geometry} material={materials.alloy} position={[1.095, 0.5, -2.2]} scale={0.31} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-0-1alloy'].geometry} material={materials.alloy} position={[1.095, 0.5, 0.95]} scale={0.31} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-1--1rubber'].geometry} material={materials.rubber} position={[-0.895, 0.5, -1.1]} scale={0.5} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-2--1rubber'].geometry} material={materials.rubber} position={[-0.895, 0.5, -2.2]} scale={0.5} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-1-1rubber'].geometry} material={materials.rubber} position={[0.895, 0.5, -1.1]} scale={0.5} />
        <mesh geometry={nodes['004-cabover-sleeperwheel-2-1rubber'].geometry} material={materials.rubber} position={[0.895, 0.5, -2.2]} scale={0.5} />
        <mesh geometry={nodes['004-cabover-sleeper22'].geometry} material={materials.glass} position={[0, 2.825, 0.879]} scale={1.5} />
        <mesh geometry={nodes['004-cabover-sleepercab-door--1'].geometry} material={materials.paint} position={[-1.113, 1.64, 0.7]} scale={0.55} />
        <mesh geometry={nodes['004-cabover-sleepercab-door-1'].geometry} material={materials.paint} position={[1.113, 1.64, 0.7]} scale={0.55} />
        <mesh geometry={nodes['004-cabover-sleeper24'].geometry} material={materials.white} position={[0, 0.935, 1.54]} scale={0.955} />
        <mesh geometry={nodes['004-cabover-sleeper26'].geometry} material={materials.accent} position={[0, 3.285, 1.2]} scale={0.805} />
        <mesh geometry={nodes['004-cabover-sleeperfifth-wheel'].geometry} material={materials.steel} position={[0, 1.165, -1.3]} scale={0.45} />
        <mesh geometry={nodes['004-cabover-sleeper18'].geometry} material={materials.steel} position={[0, 1.809, -0.695]} scale={2.405} />
        <mesh geometry={nodes['004-cabover-sleeper19'].geometry} material={materials.paint} position={[0, 2.125, 0.15]} scale={1.35} />
        <mesh geometry={nodes['004-cabover-sleeper20'].geometry} material={materials.trim} position={[0, 1.005, -0.438]} scale={1.987} />
        <mesh geometry={nodes['004-cabover-sleeper21'].geometry} material={materials.alloy} position={[0, 2.1, 0.008]} scale={1.563} />
      </group>
      <group position={[-1.2, 0, -6.9]}>
        <mesh geometry={nodes['005-refrigerated-trailerwheel-0--1rubber'].geometry} material={materials.rubber} position={[-1.04, 0.48, -5.65]} scale={0.48} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-0-1rubber'].geometry} material={materials.rubber} position={[1.04, 0.48, -5.65]} scale={0.48} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-0--1alloy'].geometry} material={materials.alloy} position={[-1.11, 0.48, -5.65]} scale={0.298} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-1--1alloy'].geometry} material={materials.alloy} position={[-1.11, 0.48, -4.55]} scale={0.298} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-2--1alloy'].geometry} material={materials.alloy} position={[-1.11, 0.48, -3.45]} scale={0.298} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-0--1steel'].geometry} material={materials.steel} position={[-1.175, 0.48, -5.65]} scale={0.194} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-0-1steel'].geometry} material={materials.steel} position={[1.205, 0.48, -5.65]} scale={0.194} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-1--1steel'].geometry} material={materials.steel} position={[-1.175, 0.48, -4.55]} scale={0.194} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-1-1steel'].geometry} material={materials.steel} position={[1.205, 0.48, -4.55]} scale={0.194} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-2--1steel'].geometry} material={materials.steel} position={[-1.175, 0.48, -3.45]} scale={0.194} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-2-1steel'].geometry} material={materials.steel} position={[1.205, 0.48, -3.45]} scale={0.194} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-0-1alloy'].geometry} material={materials.alloy} position={[1.11, 0.48, -5.65]} scale={0.298} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-1-1alloy'].geometry} material={materials.alloy} position={[1.11, 0.48, -4.55]} scale={0.298} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-2-1alloy'].geometry} material={materials.alloy} position={[1.11, 0.48, -3.45]} scale={0.298} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-1--1rubber'].geometry} material={materials.rubber} position={[-0.91, 0.48, -4.55]} scale={0.48} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-2--1rubber'].geometry} material={materials.rubber} position={[-0.91, 0.48, -3.45]} scale={0.48} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-1-1rubber'].geometry} material={materials.rubber} position={[0.91, 0.48, -4.55]} scale={0.48} />
        <mesh geometry={nodes['005-refrigerated-trailerwheel-2-1rubber'].geometry} material={materials.rubber} position={[0.91, 0.48, -3.45]} scale={0.48} />
        <mesh geometry={nodes['005-refrigerated-trailer18'].geometry} material={materials.steel} position={[0, 1.875, -0.074]} scale={6.876} />
        <mesh geometry={nodes['005-refrigerated-trailerkingpin'].geometry} material={materials.steel} position={[0, 1.16, 5.6]} scale={0.14} />
        <mesh geometry={nodes['005-refrigerated-trailer20'].geometry} material={materials.white} position={[0, 2.55, 0]} scale={6.8} />
        <mesh geometry={nodes['005-refrigerated-trailerrear-door--1'].geometry} material={materials.white} position={[-0.61, 2.48, -6.8]} scale={1.25} />
        <mesh geometry={nodes['005-refrigerated-trailerrear-door-1'].geometry} material={materials.white} position={[0.61, 2.48, -6.8]} scale={1.25} />
        <mesh geometry={nodes['005-refrigerated-trailer23'].geometry} material={materials.trim} position={[0, 2.85, 7.04]} scale={0.9} />
        <mesh geometry={nodes['005-refrigerated-trailer24'].geometry} material={materials.accent} position={[0, 0.795, -6.87]} scale={1.15} />
      </group>
      <group position={[5, 0, -6.9]}>
        <mesh geometry={nodes['006-flatbed-loadedwheel-0--1rubber'].geometry} material={materials.rubber} position={[-1.04, 0.48, -5.65]} scale={0.48} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-0-1rubber'].geometry} material={materials.rubber} position={[1.04, 0.48, -5.65]} scale={0.48} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-0--1alloy'].geometry} material={materials.alloy} position={[-1.11, 0.48, -5.65]} scale={0.298} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-1--1alloy'].geometry} material={materials.alloy} position={[-1.11, 0.48, -4.55]} scale={0.298} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-2--1alloy'].geometry} material={materials.alloy} position={[-1.11, 0.48, -3.45]} scale={0.298} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-0--1steel'].geometry} material={materials.steel} position={[-1.175, 0.48, -5.65]} scale={0.194} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-0-1steel'].geometry} material={materials.steel} position={[1.205, 0.48, -5.65]} scale={0.194} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-1--1steel'].geometry} material={materials.steel} position={[-1.175, 0.48, -4.55]} scale={0.194} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-1-1steel'].geometry} material={materials.steel} position={[1.205, 0.48, -4.55]} scale={0.194} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-2--1steel'].geometry} material={materials.steel} position={[-1.175, 0.48, -3.45]} scale={0.194} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-2-1steel'].geometry} material={materials.steel} position={[1.205, 0.48, -3.45]} scale={0.194} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-0-1alloy'].geometry} material={materials.alloy} position={[1.11, 0.48, -5.65]} scale={0.298} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-1-1alloy'].geometry} material={materials.alloy} position={[1.11, 0.48, -4.55]} scale={0.298} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-2-1alloy'].geometry} material={materials.alloy} position={[1.11, 0.48, -3.45]} scale={0.298} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-1--1rubber'].geometry} material={materials.rubber} position={[-0.91, 0.48, -4.55]} scale={0.48} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-2--1rubber'].geometry} material={materials.rubber} position={[-0.91, 0.48, -3.45]} scale={0.48} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-1-1rubber'].geometry} material={materials.rubber} position={[0.91, 0.48, -4.55]} scale={0.48} />
        <mesh geometry={nodes['006-flatbed-loadedwheel-2-1rubber'].geometry} material={materials.rubber} position={[0.91, 0.48, -3.45]} scale={0.48} />
        <mesh geometry={nodes['006-flatbed-loadedkingpin'].geometry} material={materials.steel} position={[0, 1.16, 5.6]} scale={0.14} />
        <mesh geometry={nodes['006-flatbed-loaded22'].geometry} material={materials.accent} position={[0, 0.795, -6.87]} scale={1.15} />
        <mesh geometry={nodes['006-flatbed-loaded18'].geometry} material={materials.steel} position={[0, 0.65, -0.075]} scale={6.875} />
        <mesh geometry={nodes['006-flatbed-loaded20'].geometry} material={materials.paint} position={[0, 1.9, -0.4]} scale={6.4} />
        <mesh geometry={nodes['006-flatbed-loaded21'].geometry} material={materials.trim} position={[0, 2.518, -0.4]} scale={6.135} />
      </group>
      <group position={[12, 0, -6]}>
        <mesh geometry={nodes['007-parking-bay-marking0'].geometry} material={materials.trim} position={[0, 0.007, 0]} scale={10} />
        <mesh geometry={nodes['007-parking-bay-marking1'].geometry} material={materials.white} position={[0, 0.017, 0]} scale={9.9} />
      </group>
      <group position={[12, 0.02, 0]}>
        <mesh geometry={nodes['008-cabover-day-cabwheel-0--1rubber'].geometry} material={materials.rubber} position={[-1.025, 0.5, 0.95]} scale={0.5} />
        <mesh geometry={nodes['008-cabover-day-cabwheel-0-1rubber'].geometry} material={materials.rubber} position={[1.025, 0.5, 0.95]} scale={0.5} />
        <mesh geometry={nodes['008-cabover-day-cabwheel-0--1alloy'].geometry} material={materials.alloy} position={[-1.095, 0.5, 0.95]} scale={0.31} />
        <mesh geometry={nodes['008-cabover-day-cabwheel-1--1alloy'].geometry} material={materials.alloy} position={[-1.095, 0.5, -1.7]} scale={0.31} />
        <mesh geometry={nodes['008-cabover-day-cabwheel-0--1steel'].geometry} material={materials.steel} position={[-1.16, 0.5, 0.95]} scale={0.201} />
        <mesh geometry={nodes['008-cabover-day-cabwheel-0-1steel'].geometry} material={materials.steel} position={[1.19, 0.5, 0.95]} scale={0.201} />
        <mesh geometry={nodes['008-cabover-day-cabwheel-1--1steel'].geometry} material={materials.steel} position={[-1.16, 0.5, -1.7]} scale={0.201} />
        <mesh geometry={nodes['008-cabover-day-cabwheel-1-1steel'].geometry} material={materials.steel} position={[1.19, 0.5, -1.7]} scale={0.201} />
        <mesh geometry={nodes['008-cabover-day-cabwheel-0-1alloy'].geometry} material={materials.alloy} position={[1.095, 0.5, 0.95]} scale={0.31} />
        <mesh geometry={nodes['008-cabover-day-cabwheel-1-1alloy'].geometry} material={materials.alloy} position={[1.095, 0.5, -1.7]} scale={0.31} />
        <mesh geometry={nodes['008-cabover-day-cabwheel-1--1rubber'].geometry} material={materials.rubber} position={[-0.895, 0.5, -1.7]} scale={0.5} />
        <mesh geometry={nodes['008-cabover-day-cabwheel-1-1rubber'].geometry} material={materials.rubber} position={[0.895, 0.5, -1.7]} scale={0.5} />
        <mesh geometry={nodes['008-cabover-day-cab16'].geometry} material={materials.glass} position={[0, 2.375, 0.879]} scale={1.5} />
        <mesh geometry={nodes['008-cabover-day-cabcab-door--1'].geometry} material={materials.paint} position={[-1.113, 1.64, 0.7]} scale={0.55} />
        <mesh geometry={nodes['008-cabover-day-cabcab-door-1'].geometry} material={materials.paint} position={[1.113, 1.64, 0.7]} scale={0.55} />
        <mesh geometry={nodes['008-cabover-day-cab18'].geometry} material={materials.white} position={[0, 0.935, 1.54]} scale={0.955} />
        <mesh geometry={nodes['008-cabover-day-cab20'].geometry} material={materials.accent} position={[0, 2.835, 1.2]} scale={0.805} />
        <mesh geometry={nodes['008-cabover-day-cabfifth-wheel'].geometry} material={materials.steel} position={[0, 1.165, -1.3]} scale={0.45} />
        <mesh geometry={nodes['008-cabover-day-cab14'].geometry} material={materials.trim} position={[0, 1.005, -0.438]} scale={1.987} />
        <mesh geometry={nodes['008-cabover-day-cab12'].geometry} material={materials.steel} position={[0, 1.584, -0.695]} scale={2.405} />
        <mesh geometry={nodes['008-cabover-day-cab13'].geometry} material={materials.paint} position={[0, 1.9, 0.7]} scale={1.1} />
        <mesh geometry={nodes['008-cabover-day-cab15'].geometry} material={materials.alloy} position={[0, 1.875, 0.558]} scale={1.225} />
      </group>
      <group position={[12, 0.02, -6.9]}>
        <mesh geometry={nodes['009-dry-van-trailerwheel-0--1rubber'].geometry} material={materials.rubber} position={[-1.04, 0.48, -5.65]} scale={0.48} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-0-1rubber'].geometry} material={materials.rubber} position={[1.04, 0.48, -5.65]} scale={0.48} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-0--1alloy'].geometry} material={materials.alloy} position={[-1.11, 0.48, -5.65]} scale={0.298} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-1--1alloy'].geometry} material={materials.alloy} position={[-1.11, 0.48, -4.55]} scale={0.298} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-2--1alloy'].geometry} material={materials.alloy} position={[-1.11, 0.48, -3.45]} scale={0.298} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-0--1steel'].geometry} material={materials.steel} position={[-1.175, 0.48, -5.65]} scale={0.194} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-0-1steel'].geometry} material={materials.steel} position={[1.205, 0.48, -5.65]} scale={0.194} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-1--1steel'].geometry} material={materials.steel} position={[-1.175, 0.48, -4.55]} scale={0.194} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-1-1steel'].geometry} material={materials.steel} position={[1.205, 0.48, -4.55]} scale={0.194} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-2--1steel'].geometry} material={materials.steel} position={[-1.175, 0.48, -3.45]} scale={0.194} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-2-1steel'].geometry} material={materials.steel} position={[1.205, 0.48, -3.45]} scale={0.194} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-0-1alloy'].geometry} material={materials.alloy} position={[1.11, 0.48, -5.65]} scale={0.298} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-1-1alloy'].geometry} material={materials.alloy} position={[1.11, 0.48, -4.55]} scale={0.298} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-2-1alloy'].geometry} material={materials.alloy} position={[1.11, 0.48, -3.45]} scale={0.298} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-1--1rubber'].geometry} material={materials.rubber} position={[-0.91, 0.48, -4.55]} scale={0.48} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-2--1rubber'].geometry} material={materials.rubber} position={[-0.91, 0.48, -3.45]} scale={0.48} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-1-1rubber'].geometry} material={materials.rubber} position={[0.91, 0.48, -4.55]} scale={0.48} />
        <mesh geometry={nodes['009-dry-van-trailerwheel-2-1rubber'].geometry} material={materials.rubber} position={[0.91, 0.48, -3.45]} scale={0.48} />
        <mesh geometry={nodes['009-dry-van-trailerkingpin'].geometry} material={materials.steel} position={[0, 1.16, 5.6]} scale={0.14} />
        <mesh geometry={nodes['009-dry-van-trailer20'].geometry} material={materials.white} position={[0, 2.55, 0]} scale={6.8} />
        <mesh geometry={nodes['009-dry-van-trailerrear-door--1'].geometry} material={materials.white} position={[-0.61, 2.48, -6.8]} scale={1.25} />
        <mesh geometry={nodes['009-dry-van-trailerrear-door-1'].geometry} material={materials.white} position={[0.61, 2.48, -6.8]} scale={1.25} />
        <mesh geometry={nodes['009-dry-van-trailer23'].geometry} material={materials.accent} position={[0, 0.795, -6.87]} scale={1.15} />
        <mesh geometry={nodes['009-dry-van-trailer18'].geometry} material={materials.steel} position={[0, 1.875, -0.074]} scale={6.876} />
      </group>
      <group position={[-10, 0, -4]}>
        <mesh geometry={nodes['010-weighbridge-plate0'].geometry} material={materials.steel} position={[0, 0.08, 0]} scale={9} />
        <mesh geometry={nodes['010-weighbridge-plate1'].geometry} material={materials.trim} position={[0, 0.166, 0]} scale={8.717} />
      </group>
      <group position={[-13, 0, 0]}>
        <mesh geometry={nodes['011-weigh-station-booth0'].geometry} material={materials.steel} position={[0, 1.133, 0.018]} scale={1.2} />
        <mesh geometry={nodes['011-weigh-station-booth1'].geometry} material={materials.white} position={[0, 1.325, -0.032]} scale={1.325} />
        <mesh geometry={nodes['011-weigh-station-booth2'].geometry} material={materials.paint} position={[0, 1.275, 0.993]} scale={1.175} />
        <mesh geometry={nodes['011-weigh-station-booth3'].geometry} material={materials.glass} position={[0, 1.5, 1.043]} scale={0.7} />
      </group>
      <mesh geometry={nodes['000-fuel-canopy0'].geometry} material={materials.steel} position={[0, 2.5, 0]} scale={4.04} />
      <mesh geometry={nodes['000-fuel-canopy1'].geometry} material={materials.white} position={[0, 5.2, 0]} scale={6} />
    </group>
  )
}

useGLTF.preload('/model.glb')
