"""
Fleet Intelligence Engine - Domain Risk Models
"""

import uuid
from enum import Enum
from typing import Dict, Any, List
from pydantic import BaseModel, Field
from infrastructure.intelligence.assessments.models import AssessmentResult


class DomainRiskStatus(str, Enum):
    """
    Status of an executed Domain Risk Engine.
    Represents execution state independently of the business risk quantified.
    """
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    INCONCLUSIVE = "INCONCLUSIVE"
    ERROR = "ERROR"


class RiskLevel(str, Enum):
    """
    Discrete business risk level quantified by a Domain Risk Engine.
    Avoids floating-point scores in favor of clear business severity.
    """
    UNKNOWN = "UNKNOWN"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskFinding(BaseModel):
    """
    Strongly typed domain risk finding produced by a Risk Engine.
    Avoids using generic strings for structured data.
    """
    finding_key: str
    category: str
    summary: str
    details: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    model_config = {
        "frozen": True,
        "extra": "forbid"
    }


class DomainRiskProfile(BaseModel):
    """
    Immutable profile generated by a Domain Risk Engine.
    Retains full explainability fields to allow the global recommendation engine
    to trace decisions back through assessments to the originating checks.
    """
    profile_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    risk_engine_key: str
    risk_engine_name: str
    risk_engine_version: str
    
    status: DomainRiskStatus
    risk_level: RiskLevel
    
    summary: str
    findings: List[RiskFinding] = Field(default_factory=list)
    supporting_assessments: List[AssessmentResult] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    execution_time: float = 0.0

    model_config = {
        "frozen": True,
        "extra": "forbid"
    }
