import unittest
from infrastructure.intelligence.domain_risk.models import DomainRiskProfile, RiskLevel, DomainRiskStatus
from infrastructure.intelligence.cross_domain.models import FleetInsight, InsightType, InsightStrength
from infrastructure.intelligence.fleet_health.models import VehicleIntelligenceContext, FleetHealthStatus
from infrastructure.intelligence.fleet_health.analyzer import FleetHealthAnalyzer


class TestFleetHealthPipeline(unittest.TestCase):
    def test_pipeline_integration(self):
        # 1. Domain Risks generated by individual risk engines
        v1_fuel = DomainRiskProfile(
            risk_engine_key="fuel.transaction_risk",
            risk_engine_name="Fuel Risk",
            risk_engine_version="1",
            status=DomainRiskStatus.COMPLETE,
            risk_level=RiskLevel.HIGH,
            summary="High fuel risk"
        )
        
        v1_driver = DomainRiskProfile(
            risk_engine_key="driver.behaviour_risk",
            risk_engine_name="Driver Risk",
            risk_engine_version="1",
            status=DomainRiskStatus.COMPLETE,
            risk_level=RiskLevel.HIGH,
            summary="Aggressive driving"
        )
        
        # 2. Cross Domain Intelligence generated by cross domain executor
        insight = FleetInsight(
            insight_key="cross.fuel_driver.elevated_risk",
            insight_type=InsightType.CORRELATION,
            insight_strength=InsightStrength.HIGH,
            summary="Driver behaviour causing fuel waste",
            supporting_profiles=[v1_fuel, v1_driver]
        )
        
        # 3. Fleet Health aggregation
        ctx = VehicleIntelligenceContext(
            vehicle_id="v1",
            profiles=[v1_fuel, v1_driver]
        )
        
        analyzer = FleetHealthAnalyzer(fleet_id="f1")
        report = analyzer.execute([ctx], [insight])
        
        self.assertEqual(report.fleet_health_status, FleetHealthStatus.GOOD)
        self.assertEqual(len(report.fleet_findings), 0)
        self.assertEqual(report.vehicle_count, 1)
        
        # Ensure insights are preserved
        self.assertEqual(len(report.fleet_insights), 1)
        self.assertEqual(report.fleet_insights[0].insight_key, "cross.fuel_driver.elevated_risk")
        
        # Ensure explainability back to domains
        profiles = report.fleet_insights[0].supporting_profiles
        self.assertEqual(profiles[0].risk_engine_key, "fuel.transaction_risk")
