"""
FleetGuard — Evidence Domain Model

Evidence represents immutable business entities generated by downstream
systems (like OCR, GPS gateways, or manual review).
Every piece of evidence is permanently linked to a single Operational Event.
"""

import enum
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import String, Enum, ForeignKey, Text, func
from sqlalchemy.types import JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from database import Base


class EvidenceType(str, enum.Enum):
    """Categories of evidence that can be attached to an event."""
    RECEIPT_DOCUMENT = "RECEIPT_DOCUMENT"
    OCR_EXTRACTION = "OCR_EXTRACTION"
    GPS_LOCATION = "GPS_LOCATION"
    FUEL_SENSOR = "FUEL_SENSOR"
    DRIVER_HISTORY = "DRIVER_HISTORY"
    VEHICLE_HISTORY = "VEHICLE_HISTORY"
    MANUAL_VERIFICATION = "MANUAL_VERIFICATION"


class EvidenceStatus(str, enum.Enum):
    """
    Lifecycle status of evidence generation.
    Once COMPLETED or FAILED, it is fully immutable.
    """
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class Evidence(Base):
    """
    Domain model for Evidence records.
    """
    __tablename__ = "evidence"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
    )

    event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("operational_events.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="The parent Operational Event this evidence belongs to.",
    )

    evidence_type: Mapped[EvidenceType] = mapped_column(
        Enum(EvidenceType, native_enum=False, length=50),
        nullable=False,
        index=True,
    )

    source: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="The system or user that generated this evidence (e.g., 'ocr_engine').",
    )

    status: Mapped[EvidenceStatus] = mapped_column(
        Enum(EvidenceStatus, native_enum=False, length=50),
        nullable=False,
        default=EvidenceStatus.PENDING,
        index=True,
    )

    summary: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
        doc="Short human-readable summary of the evidence.",
    )

    details: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Longer explanation or reasoning.",
    )

    raw_data: Mapped[dict[str, Any] | None] = mapped_column(
        JSON,
        nullable=True,
        doc="Schema-less JSON payload specific to the evidence type.",
    )

    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        nullable=False,
    )

    # Note: No updated_at field because Evidence is strictly immutable, 
    # except for the status which transitions from PENDING -> COMPLETED/FAILED.
    # A single timestamp is sufficient.

    def __repr__(self) -> str:
        return f"<Evidence id={self.id} type={self.evidence_type.value}>"
