"""
FleetGuard — Fleet Invite Model
Enables QR code-based fleet joining for the driver mobile app.
Each company can generate invite tokens that drivers scan to join.
"""

from datetime import datetime
from typing import Optional, TYPE_CHECKING

from sqlalchemy import Integer, String, Boolean, DateTime, ForeignKey, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from database import Base

if TYPE_CHECKING:
    from models.company import Company


class FleetInvite(Base):
    """
    Invite token for drivers to join a fleet via QR code.
    Generated by company admins through the dashboard.
    """
    __tablename__ = "fleet_invites"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    company_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="The company this invite belongs to"
    )

    invite_token: Mapped[str] = mapped_column(
        String(255), unique=True, nullable=False, index=True,
        comment="Unique token embedded in QR code"
    )

    label: Mapped[Optional[str]] = mapped_column(
        String(255), nullable=True,
        comment="Human-readable label for this invite (e.g. 'Delhi Hub Drivers')"
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True,
        comment="Whether this invite can still be used"
    )

    max_uses: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True,
        comment="Maximum number of times this invite can be used (null=unlimited)"
    )

    use_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0,
        comment="How many times this invite has been used"
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
        comment="Optional expiry date for the invite"
    )

    # --- Relationships ---
    company: Mapped["Company"] = relationship("Company", lazy="selectin")

    def __repr__(self) -> str:
        return f"<FleetInvite(id={self.id}, company_id={self.company_id}, active={self.is_active})>"

    @property
    def is_valid(self) -> bool:
        """Check if invite is still usable."""
        if not self.is_active:
            return False
        if self.max_uses is not None and self.use_count >= self.max_uses:
            return False
        if self.expires_at is not None and datetime.utcnow() > self.expires_at:
            return False
        return True
