from datetime import datetime, timedelta, timezone
from typing import Optional, TYPE_CHECKING
from sqlalchemy import Integer, String, Boolean, DateTime, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from database import Base

if TYPE_CHECKING:
    from models.company import Company
    from models.user import User

def _default_expiry():
    # 5 minutes expiry for QR token
    return datetime.now(tz=timezone.utc) + timedelta(minutes=5)

class OwnerPairingToken(Base):
    """
    Short-lived, single-use token for authenticating the Owner App via QR code.
    Generated by the Owner Dashboard and scanned by the Owner App.
    """
    __tablename__ = "owner_pairing_tokens"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    company_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True
    )
    user_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )

    pairing_token: Mapped[str] = mapped_column(
        String(255), unique=True, nullable=False, index=True
    )

    is_used: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_default_expiry
    )

    # --- Relationships ---
    company: Mapped["Company"] = relationship("Company", lazy="selectin")
    user: Mapped["User"] = relationship("User", lazy="selectin")

    @property
    def is_valid(self) -> bool:
        if self.is_used:
            return False
            
        expires = self.expires_at
        if expires.tzinfo is None:
            expires = expires.replace(tzinfo=timezone.utc)
            
        if datetime.now(tz=timezone.utc) > expires:
            return False
        return True
