"""add_fuel_root_cause_tables

Revision ID: 9dae99ddd519
Revises: 086c2d1e25f7
Create Date: 2026-08-18 20:39:57.855627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dae99ddd519'
down_revision: Union[str, None] = '086c2d1e25f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_root_cause_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anomaly_reference', sa.String(length=255), nullable=False),
    sa.Column('financial_impact_reference', sa.String(length=255), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='rc_entity_type'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_root_cause_analyses_anomaly_reference'), 'fuel_root_cause_analyses', ['anomaly_reference'], unique=True)
    op.create_index(op.f('ix_fuel_root_cause_analyses_entity_id'), 'fuel_root_cause_analyses', ['entity_id'], unique=False)
    op.create_table('fuel_root_cause_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('cause_type', sa.Enum('EXCESSIVE_IDLE', 'HIGH_SPEED', 'EXCESS_DISTANCE', 'FUEL_EVENT_ANOMALY', 'VEHICLE_MAINTENANCE', 'DRIVER_BEHAVIOUR', 'UNKNOWN', name='root_cause_type'), nullable=False),
    sa.Column('evidence_status', sa.Enum('SUPPORTING', 'NEUTRAL', 'CONTRADICTING', 'UNAVAILABLE', name='evidence_status'), nullable=False),
    sa.Column('evidence_strength', sa.Enum('NO_EVIDENCE', 'WEAK_SUPPORT', 'MODERATE_SUPPORT', 'STRONG_SUPPORT', name='evidence_strength'), nullable=False),
    sa.Column('evidence_value', sa.Float(), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('deviation_percent', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('source_references', sa.Text(), nullable=True, comment='Comma-separated IDs'),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['fuel_root_cause_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_root_cause_evidence_analysis_id'), 'fuel_root_cause_evidence', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_root_cause_evidence_analysis_id'), table_name='fuel_root_cause_evidence')
    op.drop_table('fuel_root_cause_evidence')
    op.drop_index(op.f('ix_fuel_root_cause_analyses_entity_id'), table_name='fuel_root_cause_analyses')
    op.drop_index(op.f('ix_fuel_root_cause_analyses_anomaly_reference'), table_name='fuel_root_cause_analyses')
    op.drop_table('fuel_root_cause_analyses')
    # ### end Alembic commands ###
