"""Add missing columns to documents table

Revision ID: 8f7db5b1c7a5
Revises: 20260908_1030_routing
Create Date: 2026-09-12 17:38:15.193387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f7db5b1c7a5'
down_revision: Union[str, None] = '20260908_1030_routing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'verification_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('operational_events', 'company_id',
               existing_type=sa.INTEGER(),
               comment='Tenant isolation boundary.',
               existing_nullable=False)
    op.alter_column('trips', 'expected_revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Expected revenue at time of intelligence evaluation',
               existing_nullable=True)
    op.alter_column('trips', 'expected_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Expected total cost at time of intelligence evaluation',
               existing_nullable=True)
    op.alter_column('trips', 'expected_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Expected profit at time of intelligence evaluation',
               existing_nullable=True)
    op.alter_column('trips', 'expected_margin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Expected profit margin percentage at dispatch',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_decision',
               existing_type=sa.VARCHAR(length=20),
               comment='TAKE, REVIEW, or AVOID',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the intelligence evaluation was computed',
               existing_nullable=True)
    op.alter_column('trips', 'intelligence_version',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Version of the calculation engine that produced this prediction',
               existing_nullable=True)
    op.alter_column('trips', 'confidence_level',
               existing_type=sa.VARCHAR(length=20),
               comment='HIGH, MEDIUM, LOW, INSUFFICIENT',
               existing_nullable=True)
    op.alter_column('trips', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment='LOW, MEDIUM, HIGH',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_outcome',
               existing_type=sa.VARCHAR(length=30),
               comment='OUTPERFORMED, MET_EXPECTATION, UNDERPERFORMED, LOSS, INSUFFICIENT_DATA',
               existing_nullable=True)
    op.alter_column('trips', 'intelligence_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Immutable pre-trip intelligence calculation preserved at dispatch',
               existing_nullable=True)
    op.drop_index('ix_trips_confidence_level', table_name='trips')
    op.drop_index('ix_trips_risk_level', table_name='trips')
    op.alter_column('vehicles', 'rc_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'rc_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.create_index('ix_trips_risk_level', 'trips', ['risk_level'], unique=False)
    op.create_index('ix_trips_confidence_level', 'trips', ['confidence_level'], unique=False)
    op.alter_column('trips', 'intelligence_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Immutable pre-trip intelligence calculation preserved at dispatch',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_outcome',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='OUTPERFORMED, MET_EXPECTATION, UNDERPERFORMED, LOSS, INSUFFICIENT_DATA',
               existing_nullable=True)
    op.alter_column('trips', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='LOW, MEDIUM, HIGH',
               existing_nullable=True)
    op.alter_column('trips', 'confidence_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='HIGH, MEDIUM, LOW, INSUFFICIENT',
               existing_nullable=True)
    op.alter_column('trips', 'intelligence_version',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'trip-intelligence-v1'::character varying"),
               comment=None,
               existing_comment='Version of the calculation engine that produced this prediction',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the intelligence evaluation was computed',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_decision',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='TAKE, REVIEW, or AVOID',
               existing_nullable=True)
    op.alter_column('trips', 'expected_margin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Expected profit margin percentage at dispatch',
               existing_nullable=True)
    op.alter_column('trips', 'expected_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Expected profit at time of intelligence evaluation',
               existing_nullable=True)
    op.alter_column('trips', 'expected_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Expected total cost at time of intelligence evaluation',
               existing_nullable=True)
    op.alter_column('trips', 'expected_revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Expected revenue at time of intelligence evaluation',
               existing_nullable=True)
    op.alter_column('operational_events', 'company_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tenant isolation boundary.',
               existing_nullable=False)
    op.alter_column('documents', 'verification_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
