"""Add derived fuel metrics table

Revision ID: d1c8e33c06eb
Revises: 8569eb5c85cd
Create Date: 2026-08-18 12:25:05.261990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1c8e33c06eb'
down_revision: Union[str, None] = '8569eb5c85cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derived_fuel_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='metric_entity_type'), nullable=False),
    sa.Column('metric_type', sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='fuel_metric_type'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Enum('FUEL_SENSOR', 'FUEL_TRANSACTION', 'ODOMETER_FUEL', 'MANUAL_ENTRY', 'EXTERNAL_TELEMATICS', 'ESTIMATED', name='fuel_source_type'), nullable=False),
    sa.Column('quality', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='fuel_data_quality'), nullable=False),
    sa.Column('measurement_type', sa.Enum('MEASURED', 'DERIVED', 'ESTIMATED', name='fuel_measurement_type'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True, comment='Traceability to operational data'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_derived_fuel_metrics_entity_id'), 'derived_fuel_metrics', ['entity_id'], unique=False)
    op.create_index('ix_derived_fuel_metrics_entity_period', 'derived_fuel_metrics', ['entity_type', 'entity_id', 'period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_derived_fuel_metrics_entity_type'), 'derived_fuel_metrics', ['entity_type'], unique=False)
    op.create_index(op.f('ix_derived_fuel_metrics_metric_type'), 'derived_fuel_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_derived_fuel_metrics_period_end'), 'derived_fuel_metrics', ['period_end'], unique=False)
    op.create_index(op.f('ix_derived_fuel_metrics_period_start'), 'derived_fuel_metrics', ['period_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_derived_fuel_metrics_period_start'), table_name='derived_fuel_metrics')
    op.drop_index(op.f('ix_derived_fuel_metrics_period_end'), table_name='derived_fuel_metrics')
    op.drop_index(op.f('ix_derived_fuel_metrics_metric_type'), table_name='derived_fuel_metrics')
    op.drop_index(op.f('ix_derived_fuel_metrics_entity_type'), table_name='derived_fuel_metrics')
    op.drop_index('ix_derived_fuel_metrics_entity_period', table_name='derived_fuel_metrics')
    op.drop_index(op.f('ix_derived_fuel_metrics_entity_id'), table_name='derived_fuel_metrics')
    op.drop_table('derived_fuel_metrics')
    # ### end Alembic commands ###
