"""add_entity_baselines_table

Revision ID: 8a0da79d278c
Revises: d1c8e33c06eb
Create Date: 2026-08-18 19:59:42.626965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0da79d278c'
down_revision: Union[str, None] = 'd1c8e33c06eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='baseline_entity_type'), nullable=False),
    sa.Column('metric_type', sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='baseline_fuel_metric_type'), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('calculation_method', sa.String(length=50), nullable=False),
    sa.Column('data_quality', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='baseline_data_quality'), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'INSUFFICIENT_DATA', name='baseline_status'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'entity_type', 'metric_type', 'period_start', 'period_end', name='uix_entity_baseline_period')
    )
    op.create_index(op.f('ix_entity_baselines_entity_id'), 'entity_baselines', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_baselines_entity_type'), 'entity_baselines', ['entity_type'], unique=False)
    op.create_index('ix_entity_baselines_lookup', 'entity_baselines', ['entity_id', 'entity_type', 'metric_type'], unique=False)
    op.create_index(op.f('ix_entity_baselines_metric_type'), 'entity_baselines', ['metric_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_baselines_metric_type'), table_name='entity_baselines')
    op.drop_index('ix_entity_baselines_lookup', table_name='entity_baselines')
    op.drop_index(op.f('ix_entity_baselines_entity_type'), table_name='entity_baselines')
    op.drop_index(op.f('ix_entity_baselines_entity_id'), table_name='entity_baselines')
    op.drop_table('entity_baselines')
    # ### end Alembic commands ###
