"""Add document metadata fields and fix company owner_name

Revision ID: b6b360db6af8
Revises: d54845acfb95
Create Date: 2026-08-25 01:50:37.812615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6b360db6af8'
down_revision: Union[str, None] = 'd54845acfb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'STORED', 'AVAILABLE', 'FAILED', name='documentstoragestatus', native_enum=False, length=50), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_target_id'), 'documents', ['target_id'], unique=False)
    op.create_index(op.f('ix_documents_target_type'), 'documents', ['target_type'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHING', 'PUBLISHED', name='outboxstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_event_id'), 'outbox_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operational_event_id', sa.String(length=36), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_result', sa.String(length=50), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operational_event_id', 'domain_name')
    )
    op.create_index(op.f('ix_processed_events_domain_name'), 'processed_events', ['domain_name'], unique=False)
    op.create_index(op.f('ix_processed_events_operational_event_id'), 'processed_events', ['operational_event_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Enum('RECEIPT_DOCUMENT', 'OCR_EXTRACTION', 'GPS_LOCATION', 'FUEL_SENSOR', 'DRIVER_HISTORY', 'VEHICLE_HISTORY', 'MANUAL_VERIFICATION', name='evidencetype', native_enum=False, length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='evidencestatus', native_enum=False, length=50), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_event_id'), 'evidence', ['event_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_status'), 'evidence', ['status'], unique=False)
    op.create_table('driver_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True, comment='Speed in m/s'),
    sa.Column('heading', sa.Float(), nullable=True, comment='Heading in degrees'),
    sa.Column('accuracy', sa.Float(), nullable=True, comment='GPS accuracy in meters'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='When this position was recorded on the device'),
    sa.Column('battery_percent', sa.Integer(), nullable=True),
    sa.Column('activity_state', sa.String(length=50), nullable=True, comment='Device activity: DRIVING, WALKING, STATIONARY, etc.'),
    sa.Column('source', sa.Enum('PHONE_GPS', 'HARDWARE_GPS', name='locationsource', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_locations_company_id'), 'driver_locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_driver_locations_driver_id'), 'driver_locations', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_locations_timestamp'), 'driver_locations', ['timestamp'], unique=False)
    op.create_table('location_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('GPS_DRIFT', 'SPEED_VIOLATION', 'GEOFENCE_ENTRY', 'GEOFENCE_EXIT', 'SIGNAL_LOST', name='alerttype', native_enum=False, length=50), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_alerts_alert_type'), 'location_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_location_alerts_company_id'), 'location_alerts', ['company_id'], unique=False)
    op.create_index(op.f('ix_location_alerts_driver_id'), 'location_alerts', ['driver_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('SALARY', 'ADVANCE', 'INCENTIVE', 'DEDUCTION', 'REPAYMENT', name='transactiontype', native_enum=False, length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='transactionstatus', native_enum=False, length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_company_id'), 'wallet_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_driver_id'), 'wallet_transactions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_transaction_type'), 'wallet_transactions', ['transaction_type'], unique=False)
    op.create_table('vehicle_inspections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.Enum('PRE_TRIP', 'POST_TRIP', name='inspectiontype', native_enum=False, length=50), nullable=False),
    sa.Column('overall_status', sa.Enum('PASS', 'FAIL', 'PARTIAL', name='inspectionstatus', native_enum=False, length=50), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False, comment='Checklist items: {item_name: {status, notes, photo_url}}'),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_inspections_company_id'), 'vehicle_inspections', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicle_inspections_driver_id'), 'vehicle_inspections', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicle_inspections_inspection_type'), 'vehicle_inspections', ['inspection_type'], unique=False)
    op.create_index(op.f('ix_vehicle_inspections_vehicle_id'), 'vehicle_inspections', ['vehicle_id'], unique=False)
    op.create_table('emergency_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='emergencystatus', native_enum=False, length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_alerts_company_id'), 'emergency_alerts', ['company_id'], unique=False)
    op.create_index(op.f('ix_emergency_alerts_driver_id'), 'emergency_alerts', ['driver_id'], unique=False)
    op.create_index(op.f('ix_emergency_alerts_status'), 'emergency_alerts', ['status'], unique=False)
    op.create_table('proof_of_delivery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('signature_url', sa.String(length=500), nullable=True, comment='URL to customer signature image'),
    sa.Column('photos', sa.JSON(), nullable=True, comment='List of delivery photo URLs'),
    sa.Column('invoice_url', sa.String(length=500), nullable=True, comment='URL to invoice/delivery receipt'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Delivery remarks or notes'),
    sa.Column('receiver_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proof_of_delivery_company_id'), 'proof_of_delivery', ['company_id'], unique=False)
    op.create_index(op.f('ix_proof_of_delivery_driver_id'), 'proof_of_delivery', ['driver_id'], unique=False)
    op.create_index(op.f('ix_proof_of_delivery_trip_id'), 'proof_of_delivery', ['trip_id'], unique=False)
    op.alter_column('asset_history_records', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Event-specific metadata',
               existing_nullable=True)
    op.alter_column('assets', 'business_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Authoritative business ID for the asset (e.g. internal tracking ID)',
               existing_nullable=False)
    op.alter_column('assets', 'installation_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('REGISTERED', 'INSTALLED', 'IN_STORAGE', 'IN_REPAIR', 'RETIRED', name='assetinstallationstatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('assets', 'operational_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('OK', 'WARNING', 'ERROR', 'MAINTENANCE', name='assetoperationalstatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('companies', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Legal or trading name of the company',
               existing_nullable=False)
    # Safe migration for owner_name: 
    # 1. Try to set it to the COMPANY_ADMIN's name
    op.execute("UPDATE companies SET owner_name = (SELECT full_name FROM users WHERE users.company_id = companies.id AND users.role = 'COMPANY_ADMIN' ORDER BY id ASC LIMIT 1) WHERE owner_name IS NULL")
    # 2. Fall back to company_name
    op.execute("UPDATE companies SET owner_name = company_name WHERE owner_name IS NULL")
    
    op.alter_column('companies', 'owner_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Full name of the primary company owner')
    # Safe migration for mobile_number:
    op.execute("UPDATE companies SET mobile_number = '+00000000' || id::text WHERE mobile_number IS NULL")
    
    op.alter_column('companies', 'mobile_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='Primary contact mobile number; must be globally unique')
    op.alter_column('companies', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Optional company contact email; must be globally unique if provided',
               existing_nullable=True)
    op.alter_column('companies', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', name='companystatus', native_enum=False, length=20),
               nullable=False,
               comment='Account lifecycle status',
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_index(op.f('ix_companies_mobile_number'), 'companies', ['mobile_number'], unique=True)
    op.alter_column('derived_fuel_metrics', 'entity_type',
               existing_type=postgresql.ENUM('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='metric_entity_type'),
               type_=sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='entitytypeenum', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('derived_fuel_metrics', 'metric_type',
               existing_type=postgresql.ENUM('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='fuel_metric_type'),
               type_=sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='fuelmetrictype', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('derived_fuel_metrics', 'source',
               existing_type=postgresql.ENUM('FUEL_SENSOR', 'FUEL_TRANSACTION', 'ODOMETER_FUEL', 'MANUAL_ENTRY', 'EXTERNAL_TELEMATICS', 'ESTIMATED', name='fuel_source_type'),
               type_=sa.Enum('FUEL_SENSOR', 'FUEL_TRANSACTION', 'ODOMETER_FUEL', 'MANUAL_ENTRY', 'EXTERNAL_TELEMATICS', 'ESTIMATED', name='fuelsource', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('derived_fuel_metrics', 'quality',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='fuel_data_quality'),
               type_=sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='dataquality', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('derived_fuel_metrics', 'measurement_type',
               existing_type=postgresql.ENUM('MEASURED', 'DERIVED', 'ESTIMATED', name='fuel_measurement_type'),
               type_=sa.Enum('MEASURED', 'DERIVED', 'ESTIMATED', name='measurementtype', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('drivers', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('drivers', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               comment='WhatsApp phone number in E.164 format (e.g. +919876543210)')
    op.alter_column('drivers', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='The fleet company this driver belongs to')
    op.alter_column('drivers', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Linked user account for authentication',
               existing_nullable=True)
    op.alter_column('drivers', 'verification_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Mobile app onboarding verification status',
               existing_nullable=True)
    op.alter_column('drivers', 'employment_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('FULL_TIME', 'CONTRACT', 'TEMPORARY', name='employmentstatus', native_enum=False, length=50),
               existing_nullable=True)
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='driverstatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('drivers', 'duty_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Current duty status from the mobile app',
               existing_nullable=True)
    op.alter_column('drivers', 'driver_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('drivers', 'origin_type',
               existing_type=sa.VARCHAR(length=50),
               comment="Origin of this state (e.g., 'verified_event', 'system')",
               existing_nullable=True)
    op.alter_column('drivers', 'origin_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Reference ID from the origin (e.g., OperationalEvent ID)',
               existing_nullable=True)
    op.create_index(op.f('ix_drivers_company_id'), 'drivers', ['company_id'], unique=False)
    op.drop_constraint('drivers_company_id_fkey', 'drivers', type_='foreignkey')
    op.create_foreign_key(None, 'drivers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('entity_baselines', 'entity_type',
               existing_type=postgresql.ENUM('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='baseline_entity_type'),
               type_=sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='entitytypeenum', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('entity_baselines', 'metric_type',
               existing_type=postgresql.ENUM('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='baseline_fuel_metric_type'),
               type_=sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='fuelmetrictype', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('entity_baselines', 'data_quality',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='baseline_data_quality'),
               type_=sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='dataquality', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('entity_baselines', 'status',
               existing_type=postgresql.ENUM('VALID', 'INSUFFICIENT_DATA', name='baseline_status'),
               type_=sa.Enum('VALID', 'INSUFFICIENT_DATA', name='baselinestatus', native_enum=False, length=50),
               existing_nullable=False)
    op.add_column('expenses', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('expenses', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('expenses', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('expenses', 'origin_type',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_expenses_company_id'), 'expenses', ['company_id'], unique=False)
    op.alter_column('fuel_anomalies', 'entity_type',
               existing_type=postgresql.ENUM('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='anomaly_entity_type'),
               type_=sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='entitytypeenum', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_anomalies', 'metric_type',
               existing_type=postgresql.ENUM('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='anomaly_fuel_metric_type'),
               type_=sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='fuelmetrictype', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_anomalies', 'direction',
               existing_type=postgresql.ENUM('DEGRADATION', 'IMPROVEMENT', 'NORMAL', name='anomaly_direction'),
               type_=sa.Enum('DEGRADATION', 'IMPROVEMENT', 'NORMAL', name='anomalydirection', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_anomalies', 'severity',
               existing_type=postgresql.ENUM('CRITICAL', 'WARNING', 'NORMAL', name='anomaly_severity'),
               type_=sa.Enum('CRITICAL', 'WARNING', 'NORMAL', name='anomalyseverity', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_anomalies', 'status',
               existing_type=postgresql.ENUM('ANOMALY', 'NORMAL', 'INSUFFICIENT_DATA', name='anomaly_status'),
               type_=sa.Enum('ANOMALY', 'NORMAL', 'INSUFFICIENT_DATA', name='anomalystatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_financial_impacts', 'entity_type',
               existing_type=postgresql.ENUM('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='impact_entity_type'),
               type_=sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='entitytypeenum', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_financial_impacts', 'metric_type',
               existing_type=postgresql.ENUM('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='impact_metric_type'),
               type_=sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='fuelmetrictype', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_financial_impacts', 'fuel_price_source',
               existing_type=postgresql.ENUM('ACTUAL_PURCHASE_PRICE', 'VOLUME_WEIGHTED_PURCHASE_PRICE', 'VERIFIED_HISTORICAL_REFERENCE', name='fuel_price_source'),
               type_=sa.Enum('ACTUAL_PURCHASE_PRICE', 'VOLUME_WEIGHTED_PURCHASE_PRICE', 'VERIFIED_HISTORICAL_REFERENCE', name='fuelpricesource', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of the sensor reading',
               existing_nullable=False)
    op.alter_column('fuel_logs', 'raw_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Raw fuel level reading in liters (noisy)',
               existing_nullable=False)
    op.alter_column('fuel_logs', 'filtered_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='EMA-smoothed fuel level in liters',
               existing_nullable=False)
    op.alter_column('fuel_logs', 'expected_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Expected fuel level based on distance and consumption rate',
               existing_nullable=False)
    op.alter_column('fuel_logs', 'speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Vehicle speed in km/h at time of reading',
               existing_nullable=False)
    op.alter_column('fuel_logs', 'is_theft_alert',
               existing_type=sa.BOOLEAN(),
               comment='True if this reading triggered a CRITICAL_THEFT alert',
               existing_nullable=False)
    op.create_index(op.f('ix_fuel_logs_is_theft_alert'), 'fuel_logs', ['is_theft_alert'], unique=False)
    op.create_index(op.f('ix_fuel_logs_timestamp'), 'fuel_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_fuel_logs_vehicle_id'), 'fuel_logs', ['vehicle_id'], unique=False)
    op.alter_column('fuel_root_cause_analyses', 'entity_type',
               existing_type=postgresql.ENUM('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='rc_entity_type'),
               type_=sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='entitytypeenum', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_root_cause_evidence', 'cause_type',
               existing_type=postgresql.ENUM('EXCESSIVE_IDLE', 'HIGH_SPEED', 'EXCESS_DISTANCE', 'FUEL_EVENT_ANOMALY', 'VEHICLE_MAINTENANCE', 'DRIVER_BEHAVIOUR', 'UNKNOWN', name='root_cause_type'),
               type_=sa.Enum('EXCESSIVE_IDLE', 'HIGH_SPEED', 'EXCESS_DISTANCE', 'FUEL_EVENT_ANOMALY', 'VEHICLE_MAINTENANCE', 'DRIVER_BEHAVIOUR', 'UNKNOWN', name='rootcausetype', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_root_cause_evidence', 'evidence_status',
               existing_type=postgresql.ENUM('SUPPORTING', 'NEUTRAL', 'CONTRADICTING', 'UNAVAILABLE', name='evidence_status'),
               type_=sa.Enum('SUPPORTING', 'NEUTRAL', 'CONTRADICTING', 'UNAVAILABLE', name='evidencestatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_root_cause_evidence', 'evidence_strength',
               existing_type=postgresql.ENUM('NO_EVIDENCE', 'WEAK_SUPPORT', 'MODERATE_SUPPORT', 'STRONG_SUPPORT', name='evidence_strength'),
               type_=sa.Enum('NO_EVIDENCE', 'WEAK_SUPPORT', 'MODERATE_SUPPORT', 'STRONG_SUPPORT', name='evidencestrength', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_states', 'current_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Current known fuel level in liters',
               existing_nullable=False)
    op.alter_column('fuel_states', 'source',
               existing_type=postgresql.ENUM('TELEMATICS', 'MANUAL_ENTRY', 'CALCULATED', name='fuel_source'),
               type_=sa.Enum('SENSOR', 'ESTIMATED', 'MANUAL', name='fuelsource', native_enum=False, length=50),
               comment='Origin of this state',
               existing_nullable=False)
    op.alter_column('fuel_states', 'reliability',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='fuel_state_reliability'),
               type_=sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN', name='fuelstatereliability', native_enum=False, length=50),
               comment='Business-oriented reliability of the measurement',
               existing_nullable=False)
    op.alter_column('fuel_states', 'last_operational_event_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Reference ID from the origin (e.g., OperationalEvent ID)',
               existing_nullable=True)
    op.create_index(op.f('ix_fuel_states_vehicle_id'), 'fuel_states', ['vehicle_id'], unique=True)
    op.alter_column('fuel_transactions', 'transaction_type',
               existing_type=postgresql.ENUM('REFILL', 'THEFT', 'CONSUMPTION', name='fuel_transaction_type'),
               type_=sa.Enum('FILL', 'ADJUSTMENT', name='fueltransactiontype', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('fuel_transactions', 'amount_liters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Amount of fuel changed in liters (can be positive or negative for adjustments)',
               existing_nullable=False)
    op.alter_column('fuel_transactions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the transaction occurred',
               existing_nullable=False)
    op.create_index(op.f('ix_fuel_transactions_timestamp'), 'fuel_transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_transaction_type'), 'fuel_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_vehicle_id'), 'fuel_transactions', ['vehicle_id'], unique=False)
    op.alter_column('maintenance_records', 'business_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Business identifier for the maintenance event',
               existing_nullable=False)
    op.alter_column('maintenance_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('CREATED', 'SCHEDULED', 'STARTED', 'COMPLETED', 'CANCELLED', name='maintenancestatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('maintenance_records', 'category',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('PREVENTIVE', 'CORRECTIVE', 'EMERGENCY', 'INSPECTION', name='maintenancecategory', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('maintenance_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('maintenance_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('PENDING', 'COMPLETED', 'SKIPPED', name='taskstatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('operational_events', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_comment='Globally unique event identifier (UUID v4).',
               existing_nullable=False)
    op.alter_column('operational_events', 'event_type',
               existing_type=postgresql.ENUM('FUEL_FILLED', 'FUEL_ALERT_TRIGGERED', 'TRIP_STARTED', 'TRIP_ENDED', 'TRIP_PAUSED', 'TRIP_RESUMED', 'VEHICLE_ASSIGNED', 'VEHICLE_UNASSIGNED', 'VEHICLE_STATUS_CHANGED', 'DRIVER_ASSIGNED', 'DRIVER_UNASSIGNED', 'DRIVER_STATUS_CHANGED', 'MAINTENANCE_COMPLETED', 'MAINTENANCE_SCHEDULED', 'MAINTENANCE_OVERDUE', 'TYRE_REPLACED', 'TYRE_PRESSURE_ALERT', 'EXPENSE_ADDED', 'EXPENSE_APPROVED', 'EXPENSE_REJECTED', 'INSURANCE_EXPIRY_ALERT', 'PERMIT_EXPIRY_ALERT', 'DOCUMENT_UPLOADED', 'SYSTEM_SYNC', 'FUEL_DRAINED', 'POSITION_RECORDED', 'IGNITION_STARTED', 'IGNITION_STOPPED', 'TRIP_CREATED', 'TRIP_COMPLETED', 'TRIP_CANCELLED', 'TRIP_DRIVER_ASSIGNED', 'TRIP_VEHICLE_ASSIGNED', 'VEHICLE_REGISTERED', 'DRIVER_REGISTERED', 'MAINTENANCE_CREATED', 'MAINTENANCE_STARTED', 'MAINTENANCE_CANCELLED', 'MAINTENANCE_TASK_ADDED', 'MAINTENANCE_TASK_COMPLETED', 'TYRE_REGISTERED', 'TYRE_INSTALLED', 'TYRE_REMOVED', 'TYRE_ROTATED', 'TYRE_REPAIRED', 'TYRE_RETREADED', 'TYRE_RETIRED', 'ASSET_REGISTERED', 'ASSET_INSTALLED', 'ASSET_REMOVED', 'ASSET_CALIBRATED', 'ASSET_REPAIRED', 'ASSET_REPLACED', 'ASSET_RETIRED', 'EVIDENCE_PACKAGE_READY', 'VALIDATION_SUCCEEDED', 'VALIDATION_FAILED', 'VALIDATION_DISPUTED', 'PROCESSING_COMPLETED', 'PROCESSING_FAILED', name='event_type'),
               type_=sa.Enum('FUEL_FILLED', 'FUEL_DRAINED', 'FUEL_ALERT_TRIGGERED', 'POSITION_RECORDED', 'IGNITION_STARTED', 'IGNITION_STOPPED', 'TRIP_CREATED', 'TRIP_STARTED', 'TRIP_PAUSED', 'TRIP_RESUMED', 'TRIP_COMPLETED', 'TRIP_CANCELLED', 'TRIP_DRIVER_ASSIGNED', 'TRIP_VEHICLE_ASSIGNED', 'VEHICLE_REGISTERED', 'VEHICLE_ASSIGNED', 'VEHICLE_UNASSIGNED', 'VEHICLE_STATUS_CHANGED', 'DRIVER_REGISTERED', 'DRIVER_ASSIGNED', 'DRIVER_UNASSIGNED', 'DRIVER_STATUS_CHANGED', 'MAINTENANCE_CREATED', 'MAINTENANCE_SCHEDULED', 'MAINTENANCE_STARTED', 'MAINTENANCE_COMPLETED', 'MAINTENANCE_CANCELLED', 'MAINTENANCE_OVERDUE', 'MAINTENANCE_TASK_ADDED', 'MAINTENANCE_TASK_COMPLETED', 'TYRE_REGISTERED', 'TYRE_INSTALLED', 'TYRE_REMOVED', 'TYRE_ROTATED', 'TYRE_REPAIRED', 'TYRE_RETREADED', 'TYRE_RETIRED', 'TYRE_REPLACED', 'TYRE_PRESSURE_ALERT', 'ASSET_REGISTERED', 'ASSET_INSTALLED', 'ASSET_REMOVED', 'ASSET_CALIBRATED', 'ASSET_REPAIRED', 'ASSET_REPLACED', 'ASSET_RETIRED', 'EXPENSE_ADDED', 'EXPENSE_APPROVED', 'EXPENSE_REJECTED', 'INSURANCE_EXPIRY_ALERT', 'PERMIT_EXPIRY_ALERT', 'DOCUMENT_UPLOADED', 'EVIDENCE_PACKAGE_READY', 'VALIDATION_SUCCEEDED', 'VALIDATION_FAILED', 'VALIDATION_DISPUTED', 'PROCESSING_COMPLETED', 'PROCESSING_FAILED', 'SYSTEM_SYNC', name='eventtype', native_enum=False, length=50),
               existing_comment='What happened — drives processing logic in downstream consumers.',
               existing_nullable=False)
    op.alter_column('operational_events', 'entity_type',
               existing_type=postgresql.ENUM('VEHICLE', 'DRIVER', 'TRIP', 'ROUTE', 'EXPENSE', 'MAINTENANCE', 'TYRE', 'DOCUMENT', 'SYSTEM', 'ASSET', name='entity_type'),
               type_=sa.Enum('VEHICLE', 'DRIVER', 'TRIP', 'ROUTE', 'EXPENSE', 'MAINTENANCE', 'TYRE', 'DOCUMENT', 'SYSTEM', 'ASSET', name='entitytype', native_enum=False, length=50),
               existing_comment='The primary fleet entity domain this event concerns.',
               existing_nullable=False)
    op.alter_column('operational_events', 'capture_method',
               existing_type=postgresql.ENUM('WHATSAPP_BOT', 'TELEMATICS', 'MANUAL_ENTRY', 'API_INTEGRATION', 'SYSTEM_GENERATED', name='capture_method'),
               type_=sa.Enum('WHATSAPP_BOT', 'TELEMATICS', 'MANUAL_ENTRY', 'API_INTEGRATION', 'SYSTEM_GENERATED', name='capturemethod', native_enum=False, length=50),
               existing_comment='Channel through which this event entered the system.',
               existing_nullable=False)
    op.alter_column('operational_events', 'verification_status',
               existing_type=postgresql.ENUM('PENDING', 'VERIFIED', 'DISPUTED', 'REJECTED', name='verification_status'),
               server_default=None,
               type_=sa.Enum('PENDING', 'VERIFIED', 'DISPUTED', 'REJECTED', name='verificationstatus', native_enum=False, length=50),
               existing_comment='Validation lifecycle state — updated by the Validation & Enrichment Engine.',
               existing_nullable=False)
    op.alter_column('operational_events', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               comment='ID of the user or system service that submitted this event. Null for fully automated / system-generated events.',
               existing_comment='ID of the user or system service that submitted this event. NULL for fully automated / system-generated events.',
               existing_nullable=True)
    op.alter_column('operational_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Event-specific data bag.  Schema is owned by the service producing this event_type and documented in the Event Catalogue. Maps to JSONB on PostgreSQL for indexing support.',
               existing_comment='Event-specific data bag. Schema is owned by the producing service and documented in the Event Catalogue.',
               existing_nullable=True)
    op.alter_column('operational_events', 'event_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment="Operational metadata: source IP, device ID, app version, correlation IDs, retry counts, etc.  Not business data. Named event_metadata to avoid SQLAlchemy's reserved 'metadata'.",
               existing_comment='Operational metadata: source IP, device ID, app version, correlation IDs, retry counts. Not business data.',
               existing_nullable=True)
    op.drop_index('ix_operational_events_created_at', table_name='operational_events')
    op.drop_index('ix_operational_events_entity', table_name='operational_events')
    op.alter_column('processing_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('tickets', 'issue_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Category: Tire Puncture, Fuel, Engine Repair, Food, Toll, etc.',
               existing_nullable=False)
    op.alter_column('tickets', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Claimed amount in INR',
               existing_nullable=False)
    op.alter_column('tickets', 'fair_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Regional average price for this issue_type',
               existing_nullable=True)
    op.alter_column('tickets', 'receipt_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL to the uploaded receipt image',
               existing_nullable=True)
    op.alter_column('tickets', 'ocr_raw_response',
               existing_type=sa.TEXT(),
               comment='Raw JSON response from OpenAI Vision OCR',
               existing_nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='ticketstatus'),
               type_=sa.Enum('pending', 'approved', 'rejected', name='ticketstatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('tickets', 'risk_level',
               existing_type=postgresql.ENUM('Low', 'Medium', 'High', 'Critical', name='risklevel'),
               type_=sa.Enum('Low', 'Medium', 'High', 'Critical', name='risklevel', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('tickets', 'risk_reasons',
               existing_type=sa.TEXT(),
               comment='JSON array of reasons for the risk flag',
               existing_nullable=True)
    op.alter_column('tickets', 'expense_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date extracted from receipt or reported by driver',
               existing_nullable=True)
    op.alter_column('tickets', 'payout_reference',
               existing_type=sa.VARCHAR(length=100),
               comment='UPI transaction ID after approval payout',
               existing_nullable=True)
    op.create_index(op.f('ix_tickets_driver_id'), 'tickets', ['driver_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_vehicle_id'), 'tickets', ['vehicle_id'], unique=False)
    op.alter_column('trips', 'trip_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Business identifier for the trip',
               existing_nullable=False)
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('CREATED', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'CANCELLED', name='tripstatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('trips', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Trip freight/revenue amount in base currency',
               existing_nullable=True)
    op.alter_column('trips', 'planned_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Estimated/budgeted total cost for this trip',
               existing_nullable=True)
    op.alter_column('trips', 'planned_fuel_liters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Planned fuel consumption in liters',
               existing_nullable=True)
    op.alter_column('trips', 'cargo_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Cargo weight in tonnes',
               existing_nullable=True)
    op.alter_column('trips', 'origin_type',
               existing_type=sa.VARCHAR(length=50),
               comment="Origin of this state (e.g., 'verified_event')",
               existing_nullable=True)
    op.alter_column('trips', 'origin_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Reference ID from the origin (e.g., OperationalEvent ID)',
               existing_nullable=True)
    op.alter_column('tyre_lifecycle_records', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Event-specific metadata (e.g. tread_depth, repair_cost, workshop_name)',
               existing_nullable=True)
    op.alter_column('tyres', 'serial_number',
               existing_type=sa.VARCHAR(length=255),
               comment='Authoritative business ID (physical serial number) for the tyre',
               existing_nullable=False)
    op.alter_column('tyres', 'current_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('REGISTERED', 'INSTALLED', 'IN_STORAGE', 'IN_REPAIR', 'RETREADING', 'RETIRED', name='tyrestatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('users', 'company_id',
               existing_type=sa.INTEGER(),
               comment='The company (tenant) this user belongs to',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment="User's full display name")
    op.alter_column('users', 'mobile_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='Mobile number used for login; globally unique across all tenants')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='Optional email for login; globally unique if provided')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment="bcrypt hash of the user's password — NEVER expose in API responses",
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SUPER_ADMIN', 'COMPANY_ADMIN', 'FLEET_MANAGER', 'ADMIN', 'DRIVER', name='userrole', native_enum=False, length=20),
               comment='Access level / permission role',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Soft-disable a user without deleting them')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.drop_constraint('users_company_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vehicles', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               comment='Vehicle license plate / registration',
               existing_nullable=False)
    op.alter_column('vehicles', 'vin',
               existing_type=sa.VARCHAR(length=50),
               comment='Vehicle Identification Number / Chassis Number',
               existing_nullable=True)
    op.alter_column('vehicles', 'engine_number',
               existing_type=sa.VARCHAR(length=50),
               comment='Engine Number',
               existing_nullable=True)
    op.alter_column('vehicles', 'tank_capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='Fuel tank capacity in liters',
               existing_nullable=False)
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='vehiclestatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('vehicles', 'ownership_info',
               existing_type=sa.VARCHAR(length=255),
               comment='Details about ownership (Leased, Owned, etc.)',
               existing_nullable=True)
    op.alter_column('vehicles', 'origin_type',
               existing_type=sa.VARCHAR(length=50),
               comment="Origin of this state (e.g., 'verified_event', 'system')",
               existing_nullable=True)
    op.alter_column('vehicles', 'origin_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Reference ID from the origin (e.g., OperationalEvent ID)',
               existing_nullable=True)
    op.alter_column('vehicles', 'assigned_driver_id',
               existing_type=sa.INTEGER(),
               comment='Currently assigned driver',
               existing_nullable=True)
    op.drop_constraint('trucks_license_plate_key', 'vehicles', type_='unique')
    op.create_index(op.f('ix_vehicles_company_id'), 'vehicles', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_company_id'), table_name='vehicles')
    op.create_unique_constraint('trucks_license_plate_key', 'vehicles', ['registration_number'])
    op.alter_column('vehicles', 'assigned_driver_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Currently assigned driver',
               existing_nullable=True)
    op.alter_column('vehicles', 'origin_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Reference ID from the origin (e.g., OperationalEvent ID)',
               existing_nullable=True)
    op.alter_column('vehicles', 'origin_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Origin of this state (e.g., 'verified_event', 'system')",
               existing_nullable=True)
    op.alter_column('vehicles', 'ownership_info',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Details about ownership (Leased, Owned, etc.)',
               existing_nullable=True)
    op.alter_column('vehicles', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='vehiclestatus', native_enum=False, length=50),
               server_default=sa.text("'ACTIVE'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('vehicles', 'tank_capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'400'::double precision"),
               comment=None,
               existing_comment='Fuel tank capacity in liters',
               existing_nullable=False)
    op.alter_column('vehicles', 'engine_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Engine Number',
               existing_nullable=True)
    op.alter_column('vehicles', 'vin',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Vehicle Identification Number / Chassis Number',
               existing_nullable=True)
    op.alter_column('vehicles', 'registration_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Vehicle license plate / registration',
               existing_nullable=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_company_id_fkey', 'users', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Soft-disable a user without deleting them')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'COMPANY_ADMIN', 'FLEET_MANAGER', 'ADMIN', 'DRIVER', name='userrole', native_enum=False, length=20),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Access level / permission role',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="bcrypt hash of the user's password — NEVER expose in API responses",
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='Optional email for login; globally unique if provided')
    op.alter_column('users', 'mobile_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='Mobile number used for login; globally unique across all tenants')
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment="User's full display name")
    op.alter_column('users', 'company_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='The company (tenant) this user belongs to',
               existing_nullable=False)
    op.alter_column('tyres', 'current_status',
               existing_type=sa.Enum('REGISTERED', 'INSTALLED', 'IN_STORAGE', 'IN_REPAIR', 'RETREADING', 'RETIRED', name='tyrestatus', native_enum=False, length=50),
               server_default=sa.text("'REGISTERED'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('tyres', 'serial_number',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Authoritative business ID (physical serial number) for the tyre',
               existing_nullable=False)
    op.alter_column('tyre_lifecycle_records', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Event-specific metadata (e.g. tread_depth, repair_cost, workshop_name)',
               existing_nullable=True)
    op.alter_column('trips', 'origin_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Reference ID from the origin (e.g., OperationalEvent ID)',
               existing_nullable=True)
    op.alter_column('trips', 'origin_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Origin of this state (e.g., 'verified_event')",
               existing_nullable=True)
    op.alter_column('trips', 'cargo_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Cargo weight in tonnes',
               existing_nullable=True)
    op.alter_column('trips', 'planned_fuel_liters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Planned fuel consumption in liters',
               existing_nullable=True)
    op.alter_column('trips', 'planned_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Estimated/budgeted total cost for this trip',
               existing_nullable=True)
    op.alter_column('trips', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Trip freight/revenue amount in base currency',
               existing_nullable=True)
    op.alter_column('trips', 'status',
               existing_type=sa.Enum('CREATED', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'CANCELLED', name='tripstatus', native_enum=False, length=50),
               server_default=sa.text("'CREATED'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('trips', 'trip_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Business identifier for the trip',
               existing_nullable=False)
    op.drop_index(op.f('ix_tickets_vehicle_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_driver_id'), table_name='tickets')
    op.alter_column('tickets', 'payout_reference',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='UPI transaction ID after approval payout',
               existing_nullable=True)
    op.alter_column('tickets', 'expense_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date extracted from receipt or reported by driver',
               existing_nullable=True)
    op.alter_column('tickets', 'risk_reasons',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of reasons for the risk flag',
               existing_nullable=True)
    op.alter_column('tickets', 'risk_level',
               existing_type=sa.Enum('Low', 'Medium', 'High', 'Critical', name='risklevel', native_enum=False, length=50),
               type_=postgresql.ENUM('Low', 'Medium', 'High', 'Critical', name='risklevel'),
               existing_nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='ticketstatus', native_enum=False, length=50),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='ticketstatus'),
               existing_nullable=False)
    op.alter_column('tickets', 'ocr_raw_response',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Raw JSON response from OpenAI Vision OCR',
               existing_nullable=True)
    op.alter_column('tickets', 'receipt_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL to the uploaded receipt image',
               existing_nullable=True)
    op.alter_column('tickets', 'fair_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Regional average price for this issue_type',
               existing_nullable=True)
    op.alter_column('tickets', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Claimed amount in INR',
               existing_nullable=False)
    op.alter_column('tickets', 'issue_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Category: Tire Puncture, Fuel, Engine Repair, Food, Toll, etc.',
               existing_nullable=False)
    op.alter_column('processing_records', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus', native_enum=False, length=50),
               server_default=sa.text("'PENDING'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index('ix_operational_events_entity', 'operational_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_operational_events_created_at', 'operational_events', ['created_at'], unique=False)
    op.alter_column('operational_events', 'event_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Operational metadata: source IP, device ID, app version, correlation IDs, retry counts. Not business data.',
               existing_comment="Operational metadata: source IP, device ID, app version, correlation IDs, retry counts, etc.  Not business data. Named event_metadata to avoid SQLAlchemy's reserved 'metadata'.",
               existing_nullable=True)
    op.alter_column('operational_events', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Event-specific data bag. Schema is owned by the producing service and documented in the Event Catalogue.',
               existing_comment='Event-specific data bag.  Schema is owned by the service producing this event_type and documented in the Event Catalogue. Maps to JSONB on PostgreSQL for indexing support.',
               existing_nullable=True)
    op.alter_column('operational_events', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               comment='ID of the user or system service that submitted this event. NULL for fully automated / system-generated events.',
               existing_comment='ID of the user or system service that submitted this event. Null for fully automated / system-generated events.',
               existing_nullable=True)
    op.alter_column('operational_events', 'verification_status',
               existing_type=sa.Enum('PENDING', 'VERIFIED', 'DISPUTED', 'REJECTED', name='verificationstatus', native_enum=False, length=50),
               server_default=sa.text("'PENDING'::verification_status"),
               type_=postgresql.ENUM('PENDING', 'VERIFIED', 'DISPUTED', 'REJECTED', name='verification_status'),
               existing_comment='Validation lifecycle state — updated by the Validation & Enrichment Engine.',
               existing_nullable=False)
    op.alter_column('operational_events', 'capture_method',
               existing_type=sa.Enum('WHATSAPP_BOT', 'TELEMATICS', 'MANUAL_ENTRY', 'API_INTEGRATION', 'SYSTEM_GENERATED', name='capturemethod', native_enum=False, length=50),
               type_=postgresql.ENUM('WHATSAPP_BOT', 'TELEMATICS', 'MANUAL_ENTRY', 'API_INTEGRATION', 'SYSTEM_GENERATED', name='capture_method'),
               existing_comment='Channel through which this event entered the system.',
               existing_nullable=False)
    op.alter_column('operational_events', 'entity_type',
               existing_type=sa.Enum('VEHICLE', 'DRIVER', 'TRIP', 'ROUTE', 'EXPENSE', 'MAINTENANCE', 'TYRE', 'DOCUMENT', 'SYSTEM', 'ASSET', name='entitytype', native_enum=False, length=50),
               type_=postgresql.ENUM('VEHICLE', 'DRIVER', 'TRIP', 'ROUTE', 'EXPENSE', 'MAINTENANCE', 'TYRE', 'DOCUMENT', 'SYSTEM', 'ASSET', name='entity_type'),
               existing_comment='The primary fleet entity domain this event concerns.',
               existing_nullable=False)
    op.alter_column('operational_events', 'event_type',
               existing_type=sa.Enum('FUEL_FILLED', 'FUEL_DRAINED', 'FUEL_ALERT_TRIGGERED', 'POSITION_RECORDED', 'IGNITION_STARTED', 'IGNITION_STOPPED', 'TRIP_CREATED', 'TRIP_STARTED', 'TRIP_PAUSED', 'TRIP_RESUMED', 'TRIP_COMPLETED', 'TRIP_CANCELLED', 'TRIP_DRIVER_ASSIGNED', 'TRIP_VEHICLE_ASSIGNED', 'VEHICLE_REGISTERED', 'VEHICLE_ASSIGNED', 'VEHICLE_UNASSIGNED', 'VEHICLE_STATUS_CHANGED', 'DRIVER_REGISTERED', 'DRIVER_ASSIGNED', 'DRIVER_UNASSIGNED', 'DRIVER_STATUS_CHANGED', 'MAINTENANCE_CREATED', 'MAINTENANCE_SCHEDULED', 'MAINTENANCE_STARTED', 'MAINTENANCE_COMPLETED', 'MAINTENANCE_CANCELLED', 'MAINTENANCE_OVERDUE', 'MAINTENANCE_TASK_ADDED', 'MAINTENANCE_TASK_COMPLETED', 'TYRE_REGISTERED', 'TYRE_INSTALLED', 'TYRE_REMOVED', 'TYRE_ROTATED', 'TYRE_REPAIRED', 'TYRE_RETREADED', 'TYRE_RETIRED', 'TYRE_REPLACED', 'TYRE_PRESSURE_ALERT', 'ASSET_REGISTERED', 'ASSET_INSTALLED', 'ASSET_REMOVED', 'ASSET_CALIBRATED', 'ASSET_REPAIRED', 'ASSET_REPLACED', 'ASSET_RETIRED', 'EXPENSE_ADDED', 'EXPENSE_APPROVED', 'EXPENSE_REJECTED', 'INSURANCE_EXPIRY_ALERT', 'PERMIT_EXPIRY_ALERT', 'DOCUMENT_UPLOADED', 'EVIDENCE_PACKAGE_READY', 'VALIDATION_SUCCEEDED', 'VALIDATION_FAILED', 'VALIDATION_DISPUTED', 'PROCESSING_COMPLETED', 'PROCESSING_FAILED', 'SYSTEM_SYNC', name='eventtype', native_enum=False, length=50),
               type_=postgresql.ENUM('FUEL_FILLED', 'FUEL_ALERT_TRIGGERED', 'TRIP_STARTED', 'TRIP_ENDED', 'TRIP_PAUSED', 'TRIP_RESUMED', 'VEHICLE_ASSIGNED', 'VEHICLE_UNASSIGNED', 'VEHICLE_STATUS_CHANGED', 'DRIVER_ASSIGNED', 'DRIVER_UNASSIGNED', 'DRIVER_STATUS_CHANGED', 'MAINTENANCE_COMPLETED', 'MAINTENANCE_SCHEDULED', 'MAINTENANCE_OVERDUE', 'TYRE_REPLACED', 'TYRE_PRESSURE_ALERT', 'EXPENSE_ADDED', 'EXPENSE_APPROVED', 'EXPENSE_REJECTED', 'INSURANCE_EXPIRY_ALERT', 'PERMIT_EXPIRY_ALERT', 'DOCUMENT_UPLOADED', 'SYSTEM_SYNC', 'FUEL_DRAINED', 'POSITION_RECORDED', 'IGNITION_STARTED', 'IGNITION_STOPPED', 'TRIP_CREATED', 'TRIP_COMPLETED', 'TRIP_CANCELLED', 'TRIP_DRIVER_ASSIGNED', 'TRIP_VEHICLE_ASSIGNED', 'VEHICLE_REGISTERED', 'DRIVER_REGISTERED', 'MAINTENANCE_CREATED', 'MAINTENANCE_STARTED', 'MAINTENANCE_CANCELLED', 'MAINTENANCE_TASK_ADDED', 'MAINTENANCE_TASK_COMPLETED', 'TYRE_REGISTERED', 'TYRE_INSTALLED', 'TYRE_REMOVED', 'TYRE_ROTATED', 'TYRE_REPAIRED', 'TYRE_RETREADED', 'TYRE_RETIRED', 'ASSET_REGISTERED', 'ASSET_INSTALLED', 'ASSET_REMOVED', 'ASSET_CALIBRATED', 'ASSET_REPAIRED', 'ASSET_REPLACED', 'ASSET_RETIRED', 'EVIDENCE_PACKAGE_READY', 'VALIDATION_SUCCEEDED', 'VALIDATION_FAILED', 'VALIDATION_DISPUTED', 'PROCESSING_COMPLETED', 'PROCESSING_FAILED', name='event_type'),
               existing_comment='What happened — drives processing logic in downstream consumers.',
               existing_nullable=False)
    op.alter_column('operational_events', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_comment='Globally unique event identifier (UUID v4).',
               existing_nullable=False)
    op.alter_column('maintenance_tasks', 'status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'SKIPPED', name='taskstatus', native_enum=False, length=50),
               server_default=sa.text("'PENDING'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('maintenance_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'OTHER'::character varying"),
               existing_nullable=False)
    op.alter_column('maintenance_records', 'category',
               existing_type=sa.Enum('PREVENTIVE', 'CORRECTIVE', 'EMERGENCY', 'INSPECTION', name='maintenancecategory', native_enum=False, length=50),
               server_default=sa.text("'PREVENTIVE'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('maintenance_records', 'status',
               existing_type=sa.Enum('CREATED', 'SCHEDULED', 'STARTED', 'COMPLETED', 'CANCELLED', name='maintenancestatus', native_enum=False, length=50),
               server_default=sa.text("'CREATED'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('maintenance_records', 'business_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Business identifier for the maintenance event',
               existing_nullable=False)
    op.drop_index(op.f('ix_fuel_transactions_vehicle_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_transaction_type'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_timestamp'), table_name='fuel_transactions')
    op.alter_column('fuel_transactions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the transaction occurred',
               existing_nullable=False)
    op.alter_column('fuel_transactions', 'amount_liters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Amount of fuel changed in liters (can be positive or negative for adjustments)',
               existing_nullable=False)
    op.alter_column('fuel_transactions', 'transaction_type',
               existing_type=sa.Enum('FILL', 'ADJUSTMENT', name='fueltransactiontype', native_enum=False, length=50),
               type_=postgresql.ENUM('REFILL', 'THEFT', 'CONSUMPTION', name='fuel_transaction_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_fuel_states_vehicle_id'), table_name='fuel_states')
    op.alter_column('fuel_states', 'last_operational_event_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Reference ID from the origin (e.g., OperationalEvent ID)',
               existing_nullable=True)
    op.alter_column('fuel_states', 'reliability',
               existing_type=sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN', name='fuelstatereliability', native_enum=False, length=50),
               type_=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='fuel_state_reliability'),
               comment=None,
               existing_comment='Business-oriented reliability of the measurement',
               existing_nullable=False)
    op.alter_column('fuel_states', 'source',
               existing_type=sa.Enum('SENSOR', 'ESTIMATED', 'MANUAL', name='fuelsource', native_enum=False, length=50),
               type_=postgresql.ENUM('TELEMATICS', 'MANUAL_ENTRY', 'CALCULATED', name='fuel_source'),
               comment=None,
               existing_comment='Origin of this state',
               existing_nullable=False)
    op.alter_column('fuel_states', 'current_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Current known fuel level in liters',
               existing_nullable=False)
    op.alter_column('fuel_root_cause_evidence', 'evidence_strength',
               existing_type=sa.Enum('NO_EVIDENCE', 'WEAK_SUPPORT', 'MODERATE_SUPPORT', 'STRONG_SUPPORT', name='evidencestrength', native_enum=False, length=50),
               type_=postgresql.ENUM('NO_EVIDENCE', 'WEAK_SUPPORT', 'MODERATE_SUPPORT', 'STRONG_SUPPORT', name='evidence_strength'),
               existing_nullable=False)
    op.alter_column('fuel_root_cause_evidence', 'evidence_status',
               existing_type=sa.Enum('SUPPORTING', 'NEUTRAL', 'CONTRADICTING', 'UNAVAILABLE', name='evidencestatus', native_enum=False, length=50),
               type_=postgresql.ENUM('SUPPORTING', 'NEUTRAL', 'CONTRADICTING', 'UNAVAILABLE', name='evidence_status'),
               existing_nullable=False)
    op.alter_column('fuel_root_cause_evidence', 'cause_type',
               existing_type=sa.Enum('EXCESSIVE_IDLE', 'HIGH_SPEED', 'EXCESS_DISTANCE', 'FUEL_EVENT_ANOMALY', 'VEHICLE_MAINTENANCE', 'DRIVER_BEHAVIOUR', 'UNKNOWN', name='rootcausetype', native_enum=False, length=50),
               type_=postgresql.ENUM('EXCESSIVE_IDLE', 'HIGH_SPEED', 'EXCESS_DISTANCE', 'FUEL_EVENT_ANOMALY', 'VEHICLE_MAINTENANCE', 'DRIVER_BEHAVIOUR', 'UNKNOWN', name='root_cause_type'),
               existing_nullable=False)
    op.alter_column('fuel_root_cause_analyses', 'entity_type',
               existing_type=sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='entitytypeenum', native_enum=False, length=50),
               type_=postgresql.ENUM('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='rc_entity_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_fuel_logs_vehicle_id'), table_name='fuel_logs')
    op.drop_index(op.f('ix_fuel_logs_timestamp'), table_name='fuel_logs')
    op.drop_index(op.f('ix_fuel_logs_is_theft_alert'), table_name='fuel_logs')
    op.alter_column('fuel_logs', 'is_theft_alert',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True if this reading triggered a CRITICAL_THEFT alert',
               existing_nullable=False)
    op.alter_column('fuel_logs', 'speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Vehicle speed in km/h at time of reading',
               existing_nullable=False)
    op.alter_column('fuel_logs', 'expected_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Expected fuel level based on distance and consumption rate',
               existing_nullable=False)
    op.alter_column('fuel_logs', 'filtered_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='EMA-smoothed fuel level in liters',
               existing_nullable=False)
    op.alter_column('fuel_logs', 'raw_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Raw fuel level reading in liters (noisy)',
               existing_nullable=False)
    op.alter_column('fuel_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of the sensor reading',
               existing_nullable=False)
    op.alter_column('fuel_financial_impacts', 'fuel_price_source',
               existing_type=sa.Enum('ACTUAL_PURCHASE_PRICE', 'VOLUME_WEIGHTED_PURCHASE_PRICE', 'VERIFIED_HISTORICAL_REFERENCE', name='fuelpricesource', native_enum=False, length=50),
               type_=postgresql.ENUM('ACTUAL_PURCHASE_PRICE', 'VOLUME_WEIGHTED_PURCHASE_PRICE', 'VERIFIED_HISTORICAL_REFERENCE', name='fuel_price_source'),
               existing_nullable=False)
    op.alter_column('fuel_financial_impacts', 'metric_type',
               existing_type=sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='fuelmetrictype', native_enum=False, length=50),
               type_=postgresql.ENUM('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='impact_metric_type'),
               existing_nullable=False)
    op.alter_column('fuel_financial_impacts', 'entity_type',
               existing_type=sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='entitytypeenum', native_enum=False, length=50),
               type_=postgresql.ENUM('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='impact_entity_type'),
               existing_nullable=False)
    op.alter_column('fuel_anomalies', 'status',
               existing_type=sa.Enum('ANOMALY', 'NORMAL', 'INSUFFICIENT_DATA', name='anomalystatus', native_enum=False, length=50),
               type_=postgresql.ENUM('ANOMALY', 'NORMAL', 'INSUFFICIENT_DATA', name='anomaly_status'),
               existing_nullable=False)
    op.alter_column('fuel_anomalies', 'severity',
               existing_type=sa.Enum('CRITICAL', 'WARNING', 'NORMAL', name='anomalyseverity', native_enum=False, length=50),
               type_=postgresql.ENUM('CRITICAL', 'WARNING', 'NORMAL', name='anomaly_severity'),
               existing_nullable=False)
    op.alter_column('fuel_anomalies', 'direction',
               existing_type=sa.Enum('DEGRADATION', 'IMPROVEMENT', 'NORMAL', name='anomalydirection', native_enum=False, length=50),
               type_=postgresql.ENUM('DEGRADATION', 'IMPROVEMENT', 'NORMAL', name='anomaly_direction'),
               existing_nullable=False)
    op.alter_column('fuel_anomalies', 'metric_type',
               existing_type=sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='fuelmetrictype', native_enum=False, length=50),
               type_=postgresql.ENUM('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='anomaly_fuel_metric_type'),
               existing_nullable=False)
    op.alter_column('fuel_anomalies', 'entity_type',
               existing_type=sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='entitytypeenum', native_enum=False, length=50),
               type_=postgresql.ENUM('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='anomaly_entity_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_expenses_company_id'), table_name='expenses')
    op.alter_column('expenses', 'origin_type',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'verified_event'::character varying"),
               existing_nullable=False)
    op.alter_column('expenses', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'RECORDED'::character varying"),
               existing_nullable=False)
    op.alter_column('expenses', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False)
    op.drop_column('expenses', 'company_id')
    op.alter_column('entity_baselines', 'status',
               existing_type=sa.Enum('VALID', 'INSUFFICIENT_DATA', name='baselinestatus', native_enum=False, length=50),
               type_=postgresql.ENUM('VALID', 'INSUFFICIENT_DATA', name='baseline_status'),
               existing_nullable=False)
    op.alter_column('entity_baselines', 'data_quality',
               existing_type=sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='dataquality', native_enum=False, length=50),
               type_=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='baseline_data_quality'),
               existing_nullable=False)
    op.alter_column('entity_baselines', 'metric_type',
               existing_type=sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='fuelmetrictype', native_enum=False, length=50),
               type_=postgresql.ENUM('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='baseline_fuel_metric_type'),
               existing_nullable=False)
    op.alter_column('entity_baselines', 'entity_type',
               existing_type=sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='entitytypeenum', native_enum=False, length=50),
               type_=postgresql.ENUM('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='baseline_entity_type'),
               existing_nullable=False)
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_foreign_key('drivers_company_id_fkey', 'drivers', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_drivers_company_id'), table_name='drivers')
    op.alter_column('drivers', 'origin_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Reference ID from the origin (e.g., OperationalEvent ID)',
               existing_nullable=True)
    op.alter_column('drivers', 'origin_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Origin of this state (e.g., 'verified_event', 'system')",
               existing_nullable=True)
    op.alter_column('drivers', 'driver_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'85'::double precision"),
               existing_nullable=True)
    op.alter_column('drivers', 'duty_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Current duty status from the mobile app',
               existing_nullable=True)
    op.alter_column('drivers', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='driverstatus', native_enum=False, length=50),
               server_default=sa.text("'ACTIVE'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('drivers', 'employment_status',
               existing_type=sa.Enum('FULL_TIME', 'CONTRACT', 'TEMPORARY', name='employmentstatus', native_enum=False, length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('drivers', 'verification_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Mobile app onboarding verification status',
               existing_nullable=True)
    op.alter_column('drivers', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Linked user account for authentication',
               existing_nullable=True)
    op.alter_column('drivers', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='The fleet company this driver belongs to')
    op.alter_column('drivers', 'phone_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='WhatsApp phone number in E.164 format (e.g. +919876543210)')
    op.alter_column('drivers', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('derived_fuel_metrics', 'measurement_type',
               existing_type=sa.Enum('MEASURED', 'DERIVED', 'ESTIMATED', name='measurementtype', native_enum=False, length=50),
               type_=postgresql.ENUM('MEASURED', 'DERIVED', 'ESTIMATED', name='fuel_measurement_type'),
               existing_nullable=False)
    op.alter_column('derived_fuel_metrics', 'quality',
               existing_type=sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='dataquality', native_enum=False, length=50),
               type_=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='fuel_data_quality'),
               existing_nullable=False)
    op.alter_column('derived_fuel_metrics', 'source',
               existing_type=sa.Enum('FUEL_SENSOR', 'FUEL_TRANSACTION', 'ODOMETER_FUEL', 'MANUAL_ENTRY', 'EXTERNAL_TELEMATICS', 'ESTIMATED', name='fuelsource', native_enum=False, length=50),
               type_=postgresql.ENUM('FUEL_SENSOR', 'FUEL_TRANSACTION', 'ODOMETER_FUEL', 'MANUAL_ENTRY', 'EXTERNAL_TELEMATICS', 'ESTIMATED', name='fuel_source_type'),
               existing_nullable=False)
    op.alter_column('derived_fuel_metrics', 'metric_type',
               existing_type=sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='fuelmetrictype', native_enum=False, length=50),
               type_=postgresql.ENUM('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='fuel_metric_type'),
               existing_nullable=False)
    op.alter_column('derived_fuel_metrics', 'entity_type',
               existing_type=sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='entitytypeenum', native_enum=False, length=50),
               type_=postgresql.ENUM('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='metric_entity_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_companies_mobile_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'status',
               existing_type=sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', name='companystatus', native_enum=False, length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='Account lifecycle status',
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('companies', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Optional company contact email; must be globally unique if provided',
               existing_nullable=True)
    op.alter_column('companies', 'mobile_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='Primary contact mobile number; must be globally unique')
    op.alter_column('companies', 'owner_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Full name of the primary company owner')
    op.alter_column('companies', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Legal or trading name of the company',
               existing_nullable=False)
    op.alter_column('assets', 'operational_status',
               existing_type=sa.Enum('OK', 'WARNING', 'ERROR', 'MAINTENANCE', name='assetoperationalstatus', native_enum=False, length=50),
               server_default=sa.text("'OK'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('assets', 'installation_status',
               existing_type=sa.Enum('REGISTERED', 'INSTALLED', 'IN_STORAGE', 'IN_REPAIR', 'RETIRED', name='assetinstallationstatus', native_enum=False, length=50),
               server_default=sa.text("'REGISTERED'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('assets', 'business_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Authoritative business ID for the asset (e.g. internal tracking ID)',
               existing_nullable=False)
    op.alter_column('asset_history_records', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Event-specific metadata',
               existing_nullable=True)
    op.drop_index(op.f('ix_proof_of_delivery_trip_id'), table_name='proof_of_delivery')
    op.drop_index(op.f('ix_proof_of_delivery_driver_id'), table_name='proof_of_delivery')
    op.drop_index(op.f('ix_proof_of_delivery_company_id'), table_name='proof_of_delivery')
    op.drop_table('proof_of_delivery')
    op.drop_index(op.f('ix_emergency_alerts_status'), table_name='emergency_alerts')
    op.drop_index(op.f('ix_emergency_alerts_driver_id'), table_name='emergency_alerts')
    op.drop_index(op.f('ix_emergency_alerts_company_id'), table_name='emergency_alerts')
    op.drop_table('emergency_alerts')
    op.drop_index(op.f('ix_vehicle_inspections_vehicle_id'), table_name='vehicle_inspections')
    op.drop_index(op.f('ix_vehicle_inspections_inspection_type'), table_name='vehicle_inspections')
    op.drop_index(op.f('ix_vehicle_inspections_driver_id'), table_name='vehicle_inspections')
    op.drop_index(op.f('ix_vehicle_inspections_company_id'), table_name='vehicle_inspections')
    op.drop_table('vehicle_inspections')
    op.drop_index(op.f('ix_wallet_transactions_transaction_type'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_driver_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_company_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_location_alerts_driver_id'), table_name='location_alerts')
    op.drop_index(op.f('ix_location_alerts_company_id'), table_name='location_alerts')
    op.drop_index(op.f('ix_location_alerts_alert_type'), table_name='location_alerts')
    op.drop_table('location_alerts')
    op.drop_index(op.f('ix_driver_locations_timestamp'), table_name='driver_locations')
    op.drop_index(op.f('ix_driver_locations_driver_id'), table_name='driver_locations')
    op.drop_index(op.f('ix_driver_locations_company_id'), table_name='driver_locations')
    op.drop_table('driver_locations')
    op.drop_index(op.f('ix_evidence_status'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_event_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_processed_events_operational_event_id'), table_name='processed_events')
    op.drop_index(op.f('ix_processed_events_domain_name'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_documents_target_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_target_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
