"""add_driver_age_trip_selfie

Revision ID: 8bfb490d091f
Revises: c121c0718965
Create Date: 2026-08-30 13:43:47.087624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bfb490d091f'
down_revision: Union[str, None] = 'c121c0718965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_start_selfies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('selfie_url', sa.String(length=500), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_start_selfies_company_id'), 'trip_start_selfies', ['company_id'], unique=False)
    op.create_index(op.f('ix_trip_start_selfies_driver_id'), 'trip_start_selfies', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trip_start_selfies_id'), 'trip_start_selfies', ['id'], unique=False)
    op.create_index(op.f('ix_trip_start_selfies_trip_id'), 'trip_start_selfies', ['trip_id'], unique=False)
    op.drop_index('ix_documents_target_id', table_name='documents')
    op.drop_index('ix_documents_target_type', table_name='documents')
    op.drop_column('documents', 'name')
    op.drop_column('documents', 'target_id')
    op.drop_column('documents', 'target_type')
    op.drop_column('documents', 'expiry_date')
    op.drop_column('documents', 'category')
    op.add_column('drivers', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('start_selfie_url', sa.String(length=500), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment="bcrypt hash of the user's password — NEVER expose in API responses",
               existing_comment="bcrypt hash of the user's password ù NEVER expose in API responses",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment="bcrypt hash of the user's password ù NEVER expose in API responses",
               existing_comment="bcrypt hash of the user's password — NEVER expose in API responses",
               existing_nullable=False)
    op.drop_column('trips', 'start_selfie_url')
    op.drop_column('drivers', 'age')
    op.add_column('documents', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('expiry_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('target_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_documents_target_type', 'documents', ['target_type'], unique=False)
    op.create_index('ix_documents_target_id', 'documents', ['target_id'], unique=False)
    op.drop_index(op.f('ix_trip_start_selfies_trip_id'), table_name='trip_start_selfies')
    op.drop_index(op.f('ix_trip_start_selfies_id'), table_name='trip_start_selfies')
    op.drop_index(op.f('ix_trip_start_selfies_driver_id'), table_name='trip_start_selfies')
    op.drop_index(op.f('ix_trip_start_selfies_company_id'), table_name='trip_start_selfies')
    op.drop_table('trip_start_selfies')
    # ### end Alembic commands ###
