"""vehicle_centric_locations

Revision ID: 0ca5178a52d9
Revises: 20260908_1030_routing
Create Date: 2026-09-21 10:44:08.723377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ca5178a52d9'
down_revision: Union[str, None] = '20260908_1030_routing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_current_locations',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('PHONE_GPS', 'HARDWARE_GPS', name='locationsource', native_enum=False, length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('last_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vehicle_id', 'source')
    )
    op.create_table('vehicle_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='When this position was recorded on the device'),
    sa.Column('source', sa.Enum('PHONE_GPS', 'HARDWARE_GPS', name='locationsource', native_enum=False, length=50), nullable=False),
    sa.Column('original_driver_location_id', sa.Integer(), nullable=True, comment='Reference to deprecated driver_locations table for migration audit'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_locations_company_id'), 'vehicle_locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicle_locations_device_id'), 'vehicle_locations', ['device_id'], unique=False)
    op.create_index(op.f('ix_vehicle_locations_driver_id'), 'vehicle_locations', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicle_locations_original_driver_location_id'), 'vehicle_locations', ['original_driver_location_id'], unique=True)
    op.create_index(op.f('ix_vehicle_locations_timestamp'), 'vehicle_locations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_vehicle_locations_vehicle_id'), 'vehicle_locations', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_locations_vehicle_id'), 'vehicle_locations', ['vehicle_id'], unique=False)
    op.add_column('vehicles', sa.Column('last_known_lat', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('last_known_lng', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('last_location_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vehicles', sa.Column('last_location_source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'last_location_source')
    op.drop_column('vehicles', 'last_location_at')
    op.drop_column('vehicles', 'last_known_lng')
    op.drop_column('vehicles', 'last_known_lat')
    op.drop_index(op.f('ix_vehicle_locations_vehicle_id'), table_name='vehicle_locations')
    op.drop_index(op.f('ix_vehicle_locations_timestamp'), table_name='vehicle_locations')
    op.drop_index(op.f('ix_vehicle_locations_original_driver_location_id'), table_name='vehicle_locations')
    op.drop_index(op.f('ix_vehicle_locations_driver_id'), table_name='vehicle_locations')
    op.drop_index(op.f('ix_vehicle_locations_device_id'), table_name='vehicle_locations')
    op.drop_index(op.f('ix_vehicle_locations_company_id'), table_name='vehicle_locations')
    op.drop_table('vehicle_locations')
    op.drop_table('vehicle_current_locations')
    # ### end Alembic commands ###
