"""add_fuel_anomalies_table

Revision ID: 2332f04ea585
Revises: 8a0da79d278c
Create Date: 2026-08-18 20:18:10.859375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2332f04ea585'
down_revision: Union[str, None] = '8a0da79d278c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='anomaly_entity_type'), nullable=False),
    sa.Column('metric_type', sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='anomaly_fuel_metric_type'), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('deviation_percent', sa.Float(), nullable=False),
    sa.Column('direction', sa.Enum('DEGRADATION', 'IMPROVEMENT', 'NORMAL', name='anomaly_direction'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'NORMAL', name='anomaly_severity'), nullable=False),
    sa.Column('status', sa.Enum('ANOMALY', 'NORMAL', 'INSUFFICIENT_DATA', name='anomaly_status'), nullable=False),
    sa.Column('baseline_reference', sa.String(length=255), nullable=False),
    sa.Column('observation_reference', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_reference', name='uix_fuel_anomaly_observation')
    )
    op.create_index(op.f('ix_fuel_anomalies_entity_id'), 'fuel_anomalies', ['entity_id'], unique=False)
    op.create_index(op.f('ix_fuel_anomalies_entity_type'), 'fuel_anomalies', ['entity_type'], unique=False)
    op.create_index('ix_fuel_anomalies_lookup', 'fuel_anomalies', ['entity_id', 'entity_type', 'metric_type'], unique=False)
    op.create_index(op.f('ix_fuel_anomalies_metric_type'), 'fuel_anomalies', ['metric_type'], unique=False)
    op.create_index(op.f('ix_fuel_anomalies_observation_reference'), 'fuel_anomalies', ['observation_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_anomalies_observation_reference'), table_name='fuel_anomalies')
    op.drop_index(op.f('ix_fuel_anomalies_metric_type'), table_name='fuel_anomalies')
    op.drop_index('ix_fuel_anomalies_lookup', table_name='fuel_anomalies')
    op.drop_index(op.f('ix_fuel_anomalies_entity_type'), table_name='fuel_anomalies')
    op.drop_index(op.f('ix_fuel_anomalies_entity_id'), table_name='fuel_anomalies')
    op.drop_table('fuel_anomalies')
    # ### end Alembic commands ###
