"""add_fuel_financial_impacts_table

Revision ID: 086c2d1e25f7
Revises: 2332f04ea585
Create Date: 2026-08-18 20:26:50.625368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086c2d1e25f7'
down_revision: Union[str, None] = '2332f04ea585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_financial_impacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.Enum('TRUCK', 'TRIP', 'DRIVER', 'FLEET', name='impact_entity_type'), nullable=False),
    sa.Column('metric_type', sa.Enum('FUEL_EFFICIENCY', 'FUEL_CONSUMPTION', name='impact_metric_type'), nullable=False),
    sa.Column('baseline_efficiency', sa.Float(), nullable=False),
    sa.Column('observed_efficiency', sa.Float(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('expected_fuel_liters', sa.Float(), nullable=False),
    sa.Column('implied_fuel_liters', sa.Float(), nullable=False),
    sa.Column('excess_fuel_liters', sa.Float(), nullable=False),
    sa.Column('fuel_price_per_liter', sa.Float(), nullable=False),
    sa.Column('fuel_price_source', sa.Enum('ACTUAL_PURCHASE_PRICE', 'VOLUME_WEIGHTED_PURCHASE_PRICE', 'VERIFIED_HISTORICAL_REFERENCE', name='fuel_price_source'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('estimated_financial_exposure', sa.Float(), nullable=False),
    sa.Column('anomaly_reference', sa.String(length=255), nullable=False),
    sa.Column('baseline_reference', sa.String(length=255), nullable=False),
    sa.Column('observation_reference', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculation_method', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_financial_impacts_anomaly_reference'), 'fuel_financial_impacts', ['anomaly_reference'], unique=True)
    op.create_index(op.f('ix_fuel_financial_impacts_entity_id'), 'fuel_financial_impacts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_fuel_financial_impacts_entity_type'), 'fuel_financial_impacts', ['entity_type'], unique=False)
    op.create_index(op.f('ix_fuel_financial_impacts_metric_type'), 'fuel_financial_impacts', ['metric_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_financial_impacts_metric_type'), table_name='fuel_financial_impacts')
    op.drop_index(op.f('ix_fuel_financial_impacts_entity_type'), table_name='fuel_financial_impacts')
    op.drop_index(op.f('ix_fuel_financial_impacts_entity_id'), table_name='fuel_financial_impacts')
    op.drop_index(op.f('ix_fuel_financial_impacts_anomaly_reference'), table_name='fuel_financial_impacts')
    op.drop_table('fuel_financial_impacts')
    # ### end Alembic commands ###
