"""Add internal admin and support tables

Revision ID: 73ee1c2f0419
Revises: b35f21696b99
Create Date: 2026-09-29 17:02:15.972754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73ee1c2f0419'
down_revision: Union[str, None] = 'b35f21696b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_permissions_name'), 'admin_permissions', ['name'], unique=True)
    op.create_table('admin_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('SUPER_ADMIN', 'ADMIN', 'SUPPORT_AGENT', 'OPERATIONS_ADMIN', name='adminroletype', native_enum=False, length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['admin_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_table('admin_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('ACCOUNT', 'PASSWORD_RESET', 'DRIVER', 'FLEET_OWNER', 'VEHICLE', 'TRIP', 'EXPENSE', 'PAYMENT', 'DOCUMENT', 'TECHNICAL', 'APP_BUG', 'FEATURE_REQUEST', 'COMPLAINT', 'SECURITY', 'OTHER', name='ticketcategory', native_enum=False, length=50), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING_FOR_USER', 'WAITING_INTERNAL', 'RESOLVED', 'CLOSED', 'REOPENED', name='ticketstatus', native_enum=False, length=50), nullable=False),
    sa.Column('requester_type', sa.Enum('FLEET_OWNER', 'DRIVER', 'INTERNAL_USER', name='requestertype', native_enum=False, length=50), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('requester_name', sa.String(length=255), nullable=True),
    sa.Column('requester_phone', sa.String(length=50), nullable=True),
    sa.Column('requester_email', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_ticket_id'), 'support_tickets', ['ticket_id'], unique=True)
    op.create_table('admin_password_reset_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_type', sa.Enum('FLEET_OWNER', 'DRIVER', 'INTERNAL_USER', name='requestertype', native_enum=False, length=50), nullable=False),
    sa.Column('requester_email_phone', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_ticket_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('PUBLIC', 'INTERNAL_NOTE', 'SYSTEM_EVENT', name='messagetype', native_enum=False, length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender_type', sa.Enum('FLEET_OWNER', 'DRIVER', 'INTERNAL_USER', name='requestertype', native_enum=False, length=50), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_ticket_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_type', sa.Enum('FLEET_OWNER', 'DRIVER', 'INTERNAL_USER', name='requestertype', native_enum=False, length=50), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['support_ticket_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_vehicle_locations_company_id', table_name='vehicle_locations')
    op.drop_index('ix_vehicle_locations_device_id', table_name='vehicle_locations')
    op.drop_index('ix_vehicle_locations_driver_id', table_name='vehicle_locations')
    op.drop_index('ix_vehicle_locations_event_fingerprint', table_name='vehicle_locations')
    op.drop_index('ix_vehicle_locations_original_driver_location_id', table_name='vehicle_locations')
    op.drop_index('ix_vehicle_locations_timestamp', table_name='vehicle_locations')
    op.drop_index('ix_vehicle_locations_vehicle_id', table_name='vehicle_locations')
    op.drop_table('vehicle_locations')
    op.drop_index('ix_intelligence_conditions_alert_id', table_name='intelligence_conditions')
    op.drop_index('ix_intelligence_conditions_company_id', table_name='intelligence_conditions')
    op.drop_index('ix_intelligence_conditions_driver_id', table_name='intelligence_conditions')
    op.drop_index('ix_intelligence_conditions_status', table_name='intelligence_conditions')
    op.drop_index('ix_intelligence_conditions_trip_id', table_name='intelligence_conditions')
    op.drop_index('ix_intelligence_conditions_vehicle_id', table_name='intelligence_conditions')
    op.drop_index('uq_active_condition_per_vehicle', table_name='intelligence_conditions', postgresql_where="((status)::text = 'ACTIVE'::text)")
    op.drop_table('intelligence_conditions')
    op.drop_table('vehicle_current_locations')
    op.alter_column('documents', 'verification_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_column('documents', 'name_encrypted')
    op.drop_column('driver_locations', 'latitude_encrypted')
    op.drop_column('driver_locations', 'longitude_encrypted')
    op.drop_index('uq_drivers_phone_number_blind', table_name='drivers')
    op.drop_column('drivers', 'phone_number_encrypted')
    op.drop_column('drivers', 'phone_number_blind')
    op.alter_column('expenses', 'reviewed_by',
               existing_type=sa.VARCHAR(length=255),
               comment='User ID of the admin who approved/rejected',
               existing_nullable=True)
    op.alter_column('expenses', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of approval/rejection',
               existing_nullable=True)
    op.alter_column('expenses', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment='Reason for rejection, required when rejecting',
               existing_nullable=True)
    op.drop_column('expenses', 'amount_encrypted')
    op.alter_column('location_alerts', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('operational_events', 'company_id',
               existing_type=sa.INTEGER(),
               comment='Tenant isolation boundary.',
               existing_nullable=False)
    op.add_column('trips', sa.Column('receiver_name', sa.String(length=255), nullable=True))
    op.add_column('trips', sa.Column('receiver_phone', sa.String(length=50), nullable=True))
    op.add_column('trips', sa.Column('receiver_company', sa.String(length=255), nullable=True))
    op.add_column('trips', sa.Column('receiver_address', sa.Text(), nullable=True))
    op.add_column('trips', sa.Column('receiver_city', sa.String(length=100), nullable=True))
    op.add_column('trips', sa.Column('receiver_state', sa.String(length=100), nullable=True))
    op.add_column('trips', sa.Column('receiver_pincode', sa.String(length=20), nullable=True))
    op.add_column('trips', sa.Column('receiver_notes', sa.Text(), nullable=True))
    op.alter_column('trips', 'expected_revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Expected revenue at time of intelligence evaluation',
               existing_nullable=True)
    op.alter_column('trips', 'expected_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Expected total cost at time of intelligence evaluation',
               existing_nullable=True)
    op.alter_column('trips', 'expected_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Expected profit at time of intelligence evaluation',
               existing_nullable=True)
    op.alter_column('trips', 'expected_margin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Expected profit margin percentage at dispatch',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_decision',
               existing_type=sa.VARCHAR(length=20),
               comment='TAKE, REVIEW, or AVOID',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the intelligence evaluation was computed',
               existing_nullable=True)
    op.alter_column('trips', 'intelligence_version',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Version of the calculation engine that produced this prediction',
               existing_nullable=True)
    op.alter_column('trips', 'confidence_level',
               existing_type=sa.VARCHAR(length=20),
               comment='HIGH, MEDIUM, LOW, INSUFFICIENT',
               existing_nullable=True)
    op.alter_column('trips', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment='LOW, MEDIUM, HIGH',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_outcome',
               existing_type=sa.VARCHAR(length=30),
               comment='OUTPERFORMED, MET_EXPECTATION, UNDERPERFORMED, LOSS, INSUFFICIENT_DATA',
               existing_nullable=True)
    op.alter_column('trips', 'intelligence_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Immutable pre-trip intelligence calculation preserved at dispatch',
               existing_nullable=True)
    op.alter_column('trips', 'customer_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Customer/company name for this trip',
               existing_nullable=True)
    op.alter_column('trips', 'customer_phone',
               existing_type=sa.VARCHAR(length=50),
               comment='Customer contact phone number',
               existing_nullable=True)
    op.alter_column('trips', 'customer_contact_person',
               existing_type=sa.VARCHAR(length=255),
               comment='Contact person at customer site',
               existing_nullable=True)
    op.alter_column('trips', 'instructions',
               existing_type=sa.TEXT(),
               comment='Delivery/handling instructions for the driver',
               existing_nullable=True)
    op.drop_index('ix_trips_confidence_level', table_name='trips')
    op.drop_index('ix_trips_risk_level', table_name='trips')
    op.drop_column('trips', 'destination_lng_encrypted')
    op.drop_column('trips', 'revenue_encrypted')
    op.drop_column('trips', 'origin_lng_encrypted')
    op.drop_column('trips', 'origin_lat_encrypted')
    op.drop_column('trips', 'expected_revenue_encrypted')
    op.drop_column('trips', 'destination_lat_encrypted')
    op.alter_column('vehicles', 'rc_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('vehicles', 'last_known_lng')
    op.drop_column('vehicles', 'last_location_at')
    op.drop_column('vehicles', 'last_location_source')
    op.drop_column('vehicles', 'last_known_lat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('last_known_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('last_location_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('last_location_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('last_known_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('vehicles', 'rc_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('trips', sa.Column('destination_lat_encrypted', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('expected_revenue_encrypted', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('origin_lat_encrypted', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('origin_lng_encrypted', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('revenue_encrypted', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('destination_lng_encrypted', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.create_index('ix_trips_risk_level', 'trips', ['risk_level'], unique=False)
    op.create_index('ix_trips_confidence_level', 'trips', ['confidence_level'], unique=False)
    op.alter_column('trips', 'instructions',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Delivery/handling instructions for the driver',
               existing_nullable=True)
    op.alter_column('trips', 'customer_contact_person',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Contact person at customer site',
               existing_nullable=True)
    op.alter_column('trips', 'customer_phone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Customer contact phone number',
               existing_nullable=True)
    op.alter_column('trips', 'customer_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Customer/company name for this trip',
               existing_nullable=True)
    op.alter_column('trips', 'intelligence_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Immutable pre-trip intelligence calculation preserved at dispatch',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_outcome',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='OUTPERFORMED, MET_EXPECTATION, UNDERPERFORMED, LOSS, INSUFFICIENT_DATA',
               existing_nullable=True)
    op.alter_column('trips', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='LOW, MEDIUM, HIGH',
               existing_nullable=True)
    op.alter_column('trips', 'confidence_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='HIGH, MEDIUM, LOW, INSUFFICIENT',
               existing_nullable=True)
    op.alter_column('trips', 'intelligence_version',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'trip-intelligence-v1'::character varying"),
               comment=None,
               existing_comment='Version of the calculation engine that produced this prediction',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the intelligence evaluation was computed',
               existing_nullable=True)
    op.alter_column('trips', 'recommendation_decision',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='TAKE, REVIEW, or AVOID',
               existing_nullable=True)
    op.alter_column('trips', 'expected_margin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Expected profit margin percentage at dispatch',
               existing_nullable=True)
    op.alter_column('trips', 'expected_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Expected profit at time of intelligence evaluation',
               existing_nullable=True)
    op.alter_column('trips', 'expected_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Expected total cost at time of intelligence evaluation',
               existing_nullable=True)
    op.alter_column('trips', 'expected_revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Expected revenue at time of intelligence evaluation',
               existing_nullable=True)
    op.drop_column('trips', 'receiver_notes')
    op.drop_column('trips', 'receiver_pincode')
    op.drop_column('trips', 'receiver_state')
    op.drop_column('trips', 'receiver_city')
    op.drop_column('trips', 'receiver_address')
    op.drop_column('trips', 'receiver_company')
    op.drop_column('trips', 'receiver_phone')
    op.drop_column('trips', 'receiver_name')
    op.alter_column('operational_events', 'company_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tenant isolation boundary.',
               existing_nullable=False)
    op.alter_column('location_alerts', 'details',
               existing_type=sa.String(length=500),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('expenses', sa.Column('amount_encrypted', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.alter_column('expenses', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Reason for rejection, required when rejecting',
               existing_nullable=True)
    op.alter_column('expenses', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of approval/rejection',
               existing_nullable=True)
    op.alter_column('expenses', 'reviewed_by',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='User ID of the admin who approved/rejected',
               existing_nullable=True)
    op.add_column('drivers', sa.Column('phone_number_blind', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('phone_number_encrypted', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.create_index('uq_drivers_phone_number_blind', 'drivers', ['phone_number_blind'], unique=True)
    op.add_column('driver_locations', sa.Column('longitude_encrypted', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('driver_locations', sa.Column('latitude_encrypted', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('name_encrypted', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.alter_column('documents', 'verification_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.create_table('vehicle_current_locations',
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('heading', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['assets.id'], name='vehicle_current_locations_device_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name='vehicle_current_locations_driver_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='vehicle_current_locations_vehicle_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vehicle_id', 'source', name='vehicle_current_locations_pkey')
    )
    op.create_table('intelligence_conditions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('condition_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_evaluated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_event_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('alert_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['location_alerts.id'], name='intelligence_conditions_alert_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='intelligence_conditions_company_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name='intelligence_conditions_driver_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='intelligence_conditions_trip_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='intelligence_conditions_vehicle_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='intelligence_conditions_pkey')
    )
    op.create_index('uq_active_condition_per_vehicle', 'intelligence_conditions', ['company_id', 'vehicle_id', 'condition_type'], unique=True, postgresql_where="((status)::text = 'ACTIVE'::text)")
    op.create_index('ix_intelligence_conditions_vehicle_id', 'intelligence_conditions', ['vehicle_id'], unique=False)
    op.create_index('ix_intelligence_conditions_trip_id', 'intelligence_conditions', ['trip_id'], unique=False)
    op.create_index('ix_intelligence_conditions_status', 'intelligence_conditions', ['status'], unique=False)
    op.create_index('ix_intelligence_conditions_driver_id', 'intelligence_conditions', ['driver_id'], unique=False)
    op.create_index('ix_intelligence_conditions_company_id', 'intelligence_conditions', ['company_id'], unique=False)
    op.create_index('ix_intelligence_conditions_alert_id', 'intelligence_conditions', ['alert_id'], unique=False)
    op.create_table('vehicle_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('heading', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='When this position was recorded on the device'),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('original_driver_location_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Reference to deprecated driver_locations table for migration audit'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('event_fingerprint', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='vehicle_locations_company_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['assets.id'], name='vehicle_locations_device_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name='vehicle_locations_driver_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='vehicle_locations_vehicle_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vehicle_locations_pkey')
    )
    op.create_index('ix_vehicle_locations_vehicle_id', 'vehicle_locations', ['vehicle_id'], unique=False)
    op.create_index('ix_vehicle_locations_timestamp', 'vehicle_locations', ['timestamp'], unique=False)
    op.create_index('ix_vehicle_locations_original_driver_location_id', 'vehicle_locations', ['original_driver_location_id'], unique=True)
    op.create_index('ix_vehicle_locations_event_fingerprint', 'vehicle_locations', ['event_fingerprint'], unique=True)
    op.create_index('ix_vehicle_locations_driver_id', 'vehicle_locations', ['driver_id'], unique=False)
    op.create_index('ix_vehicle_locations_device_id', 'vehicle_locations', ['device_id'], unique=False)
    op.create_index('ix_vehicle_locations_company_id', 'vehicle_locations', ['company_id'], unique=False)
    op.drop_table('support_ticket_attachments')
    op.drop_table('support_ticket_messages')
    op.drop_table('admin_password_reset_requests')
    op.drop_index(op.f('ix_support_tickets_ticket_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_table('admin_notifications')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_table('admin_role_permissions')
    op.drop_table('admin_roles')
    op.drop_index(op.f('ix_admin_permissions_name'), table_name='admin_permissions')
    op.drop_table('admin_permissions')
    # ### end Alembic commands ###
