"""Add event_fingerprint and source_metadata

Revision ID: e578cf4cf607
Revises: 0ca5178a52d9
Create Date: 2026-09-21 11:54:34.755680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e578cf4cf607'
down_revision: Union[str, None] = '0ca5178a52d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # Check vehicle_current_locations
    cols = [c['name'] for c in inspector.get_columns('vehicle_current_locations')]
    if 'source_metadata' not in cols:
        op.add_column('vehicle_current_locations', sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        
    # Check vehicle_locations
    cols_vl = [c['name'] for c in inspector.get_columns('vehicle_locations')]
    if 'event_fingerprint' not in cols_vl:
        op.add_column('vehicle_locations', sa.Column('event_fingerprint', sa.String(length=255), nullable=True, comment='Deterministic hash to prevent duplicate locations'))
        op.create_index(op.f('ix_vehicle_locations_event_fingerprint'), 'vehicle_locations', ['event_fingerprint'], unique=True)
    
    if 'source_metadata' not in cols_vl:
        op.add_column('vehicle_locations', sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_locations_event_fingerprint'), table_name='vehicle_locations')
    op.drop_column('vehicle_locations', 'source_metadata')
    op.drop_column('vehicle_locations', 'event_fingerprint')
    op.drop_column('vehicle_current_locations', 'source_metadata')
    # ### end Alembic commands ###
