"""
Fleet Intelligence Engine - Global Decision Models
"""

import uuid
from enum import Enum
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field
from infrastructure.intelligence.domain_risk.models import DomainRiskProfile


class DecisionStatus(str, Enum):
    """
    Status of an executed Global Decision Engine.
    Represents execution state independently of the final business recommendation.
    """
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    INCONCLUSIVE = "INCONCLUSIVE"
    ERROR = "ERROR"


class RecommendationStatus(str, Enum):
    """
    Discrete final business recommendation.
    """
    APPROVE = "APPROVE"
    APPROVE_WITH_REVIEW = "APPROVE_WITH_REVIEW"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REJECT = "REJECT"


class RecommendationFinding(BaseModel):
    """
    Strongly typed finding produced by the Global Decision Engine.
    """
    finding_key: str
    category: str
    summary: str
    details: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    model_config = {
        "frozen": True,
        "extra": "forbid"
    }


class Recommendation(BaseModel):
    """
    Immutable final recommendation generated by a Decision Engine.
    Retains full explainability fields to allow clients to trace decisions
    back through domain risk profiles, assessments, checks, and evidence.
    """
    recommendation_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    decision_engine_key: str
    decision_engine_name: str
    decision_engine_version: str
    
    status: DecisionStatus
    recommendation: Optional[RecommendationStatus] = None
    
    summary: str
    findings: List[RecommendationFinding] = Field(default_factory=list)
    supporting_profiles: List[DomainRiskProfile] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    execution_time: float = 0.0

    model_config = {
        "frozen": True,
        "extra": "forbid"
    }
